// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActorsColumns holds the columns for the "actors" table.
	ActorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeString},
		{Name: "source_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "name_zht", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"female", "male", "unknown"}, Default: "unknown"},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
	}
	// ActorsTable holds the schema information for the "actors" table.
	ActorsTable = &schema.Table{
		Name:       "actors",
		Columns:    ActorsColumns,
		PrimaryKey: []*schema.Column{ActorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "actor_provider_source_id",
				Unique:  true,
				Columns: []*schema.Column{ActorsColumns[3], ActorsColumns[4]},
			},
		},
	}
	// EmbyNotificationsColumns holds the columns for the "emby_notifications" table.
	EmbyNotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "revision", Type: field.TypeInt, Default: 1},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime},
		{Name: "last_error", Type: field.TypeString, Default: ""},
	}
	// EmbyNotificationsTable holds the schema information for the "emby_notifications" table.
	EmbyNotificationsTable = &schema.Table{
		Name:       "emby_notifications",
		Columns:    EmbyNotificationsColumns,
		PrimaryKey: []*schema.Column{EmbyNotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "embynotification_next_attempt_at",
				Unique:  false,
				Columns: []*schema.Column{EmbyNotificationsColumns[6]},
			},
		},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "file_id", Type: field.TypeString, Unique: true},
		{Name: "pick_code", Type: field.TypeString, Default: ""},
		{Name: "sha1", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "parent_id", Type: field.TypeString, Default: ""},
		{Name: "account_id", Type: field.TypeString, Default: ""},
		{Name: "root_id", Type: field.TypeString, Default: ""},
		{Name: "path", Type: field.TypeString, Default: ""},
		{Name: "scan_id", Type: field.TypeString, Default: ""},
		{Name: "movie_files", Type: field.TypeInt, Nullable: true},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_movies_files",
				Columns:    []*schema.Column{FilesColumns[13]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "file_account_id_root_id_scan_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[9], FilesColumns[10], FilesColumns[12]},
			},
			{
				Name:    "file_movie_files_account_id_root_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[13], FilesColumns[9], FilesColumns[10]},
			},
		},
	}
	// MetadataCachesColumns holds the columns for the "metadata_caches" table.
	MetadataCachesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "result", Type: field.TypeJSON, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// MetadataCachesTable holds the schema information for the "metadata_caches" table.
	MetadataCachesTable = &schema.Table{
		Name:       "metadata_caches",
		Columns:    MetadataCachesColumns,
		PrimaryKey: []*schema.Column{MetadataCachesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "metadatacache_provider_code",
				Unique:  true,
				Columns: []*schema.Column{MetadataCachesColumns[1], MetadataCachesColumns[2]},
			},
		},
	}
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "manual_code", Type: field.TypeString, Default: ""},
		{Name: "canonical_code", Type: field.TypeString, Default: ""},
		{Name: "javdb_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "release_date", Type: field.TypeTime, Nullable: true},
		{Name: "duration", Type: field.TypeInt, Nullable: true},
		{Name: "director_id", Type: field.TypeString, Nullable: true},
		{Name: "director_name", Type: field.TypeString, Nullable: true},
		{Name: "maker_id", Type: field.TypeString, Nullable: true},
		{Name: "maker_name", Type: field.TypeString, Nullable: true},
		{Name: "series_id", Type: field.TypeString, Nullable: true},
		{Name: "series_name", Type: field.TypeString, Nullable: true},
		{Name: "rating", Type: field.TypeFloat64, Nullable: true},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "poster", Type: field.TypeString, Nullable: true},
		{Name: "fanarts", Type: field.TypeJSON},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata_snapshot", Type: field.TypeJSON, Nullable: true},
		{Name: "scrape_status", Type: field.TypeEnum, Enums: []string{"pending", "done", "failed"}, Default: "pending"},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "movie_canonical_code",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[5]},
			},
			{
				Name:    "movie_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[1], MoviesColumns[0]},
			},
		},
	}
	// OfflineDownloadsColumns holds the columns for the "offline_downloads" table.
	OfflineDownloadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString, Default: ""},
		{Name: "javdb_id", Type: field.TypeString, Default: ""},
		{Name: "hash", Type: field.TypeString},
		{Name: "info_hash", Type: field.TypeString, Default: ""},
		{Name: "account_id", Type: field.TypeString, Default: ""},
		{Name: "directory_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "done", "failed"}, Default: "running"},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "file_id", Type: field.TypeString, Default: ""},
		{Name: "file_ids", Type: field.TypeJSON},
		{Name: "scan_task_id", Type: field.TypeInt, Default: 0},
		{Name: "awaiting_location", Type: field.TypeBool, Default: false},
	}
	// OfflineDownloadsTable holds the schema information for the "offline_downloads" table.
	OfflineDownloadsTable = &schema.Table{
		Name:       "offline_downloads",
		Columns:    OfflineDownloadsColumns,
		PrimaryKey: []*schema.Column{OfflineDownloadsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "offlinedownload_account_id_status_hash",
				Unique:  false,
				Columns: []*schema.Column{OfflineDownloadsColumns[7], OfflineDownloadsColumns[9], OfflineDownloadsColumns[5]},
			},
			{
				Name:    "offlinedownload_account_id_directory_id_hash_id",
				Unique:  false,
				Columns: []*schema.Column{OfflineDownloadsColumns[7], OfflineDownloadsColumns[8], OfflineDownloadsColumns[5], OfflineDownloadsColumns[0]},
			},
			{
				Name:    "offlinedownload_account_id_javdb_id_hash_id",
				Unique:  false,
				Columns: []*schema.Column{OfflineDownloadsColumns[7], OfflineDownloadsColumns[4], OfflineDownloadsColumns[5], OfflineDownloadsColumns[0]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeJSON},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"movie", "actor"}, Default: "movie"},
		{Name: "target_id", Type: field.TypeString},
		{Name: "code", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "cover", Type: field.TypeString, Default: ""},
		{Name: "release_date", Type: field.TypeString, Default: ""},
		{Name: "origin_id", Type: field.TypeInt, Nullable: true},
		{Name: "auto_download", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"waiting", "added", "stale", "active", "paused"}, Default: "waiting"},
		{Name: "cursor", Type: field.TypeString, Default: ""},
		{Name: "hash", Type: field.TypeString, Default: ""},
		{Name: "task_id", Type: field.TypeInt, Nullable: true},
		{Name: "next_check_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "checks", Type: field.TypeInt, Default: 0},
		{Name: "error", Type: field.TypeString, Nullable: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_kind_target_id",
				Unique:  true,
				Columns: []*schema.Column{SubscriptionsColumns[3], SubscriptionsColumns[4]},
			},
			{
				Name:    "subscription_status_next_check_at",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[11], SubscriptionsColumns[15]},
			},
		},
	}
	// SubtitlesColumns holds the columns for the "subtitles" table.
	SubtitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "language", Type: field.TypeString, Default: "zh-CN"},
		{Name: "format", Type: field.TypeString, Default: "srt"},
		{Name: "version_tag", Type: field.TypeString, Default: "standard"},
		{Name: "source", Type: field.TypeString, Default: "local"},
		{Name: "source_url", Type: field.TypeString, Default: ""},
		{Name: "storage_path", Type: field.TypeString, Default: ""},
		{Name: "movie_id", Type: field.TypeInt},
	}
	// SubtitlesTable holds the schema information for the "subtitles" table.
	SubtitlesTable = &schema.Table{
		Name:       "subtitles",
		Columns:    SubtitlesColumns,
		PrimaryKey: []*schema.Column{SubtitlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subtitles_movies_subtitles",
				Columns:    []*schema.Column{SubtitlesColumns[10]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subtitle_movie_id",
				Unique:  false,
				Columns: []*schema.Column{SubtitlesColumns[10]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "provider", Type: field.TypeString},
		{Name: "source_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "name_zht", Type: field.TypeString, Nullable: true},
		{Name: "category_id", Type: field.TypeString, Default: ""},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tag_provider_source_id",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[3], TagsColumns[4]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"queued", "running", "done", "failed"}, Default: "queued"},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "retry_at", Type: field.TypeTime, Nullable: true},
		{Name: "resource_key", Type: field.TypeString, Default: ""},
		{Name: "error", Type: field.TypeString, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_type_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3], TasksColumns[4]},
			},
			{
				Name:    "task_type_status_retry_at",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3], TasksColumns[4], TasksColumns[8]},
			},
			{
				Name:    "task_resource_key_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[9], TasksColumns[4]},
			},
			{
				Name:    "task_type",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3]},
			},
		},
	}
	// ViewedMoviesColumns holds the columns for the "viewed_movies" table.
	ViewedMoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "javdb_id", Type: field.TypeString, Unique: true},
		{Name: "viewed_at", Type: field.TypeTime},
	}
	// ViewedMoviesTable holds the schema information for the "viewed_movies" table.
	ViewedMoviesTable = &schema.Table{
		Name:       "viewed_movies",
		Columns:    ViewedMoviesColumns,
		PrimaryKey: []*schema.Column{ViewedMoviesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "viewedmovie_viewed_at_id",
				Unique:  false,
				Columns: []*schema.Column{ViewedMoviesColumns[2], ViewedMoviesColumns[0]},
			},
		},
	}
	// MovieActorsColumns holds the columns for the "movie_actors" table.
	MovieActorsColumns = []*schema.Column{
		{Name: "movie_id", Type: field.TypeInt},
		{Name: "actor_id", Type: field.TypeInt},
	}
	// MovieActorsTable holds the schema information for the "movie_actors" table.
	MovieActorsTable = &schema.Table{
		Name:       "movie_actors",
		Columns:    MovieActorsColumns,
		PrimaryKey: []*schema.Column{MovieActorsColumns[0], MovieActorsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "movie_actors_movie_id",
				Columns:    []*schema.Column{MovieActorsColumns[0]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "movie_actors_actor_id",
				Columns:    []*schema.Column{MovieActorsColumns[1]},
				RefColumns: []*schema.Column{ActorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MovieTagsColumns holds the columns for the "movie_tags" table.
	MovieTagsColumns = []*schema.Column{
		{Name: "movie_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// MovieTagsTable holds the schema information for the "movie_tags" table.
	MovieTagsTable = &schema.Table{
		Name:       "movie_tags",
		Columns:    MovieTagsColumns,
		PrimaryKey: []*schema.Column{MovieTagsColumns[0], MovieTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "movie_tags_movie_id",
				Columns:    []*schema.Column{MovieTagsColumns[0]},
				RefColumns: []*schema.Column{MoviesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "movie_tags_tag_id",
				Columns:    []*schema.Column{MovieTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActorsTable,
		EmbyNotificationsTable,
		FilesTable,
		MetadataCachesTable,
		MoviesTable,
		OfflineDownloadsTable,
		SettingsTable,
		SubscriptionsTable,
		SubtitlesTable,
		TagsTable,
		TasksTable,
		ViewedMoviesTable,
		MovieActorsTable,
		MovieTagsTable,
	}
)

func init() {
	FilesTable.ForeignKeys[0].RefTable = MoviesTable
	SubtitlesTable.ForeignKeys[0].RefTable = MoviesTable
	MovieActorsTable.ForeignKeys[0].RefTable = MoviesTable
	MovieActorsTable.ForeignKeys[1].RefTable = ActorsTable
	MovieTagsTable.ForeignKeys[0].RefTable = MoviesTable
	MovieTagsTable.ForeignKeys[1].RefTable = TagsTable
}
