// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/ppxb/miyabi/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ppxb/miyabi/internal/ent/actor"
	"github.com/ppxb/miyabi/internal/ent/embynotification"
	"github.com/ppxb/miyabi/internal/ent/file"
	"github.com/ppxb/miyabi/internal/ent/metadatacache"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/offlinedownload"
	"github.com/ppxb/miyabi/internal/ent/setting"
	"github.com/ppxb/miyabi/internal/ent/subscription"
	"github.com/ppxb/miyabi/internal/ent/subtitle"
	"github.com/ppxb/miyabi/internal/ent/tag"
	"github.com/ppxb/miyabi/internal/ent/task"
	"github.com/ppxb/miyabi/internal/ent/viewedmovie"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Actor is the client for interacting with the Actor builders.
	Actor *ActorClient
	// EmbyNotification is the client for interacting with the EmbyNotification builders.
	EmbyNotification *EmbyNotificationClient
	// File is the client for interacting with the File builders.
	File *FileClient
	// MetadataCache is the client for interacting with the MetadataCache builders.
	MetadataCache *MetadataCacheClient
	// Movie is the client for interacting with the Movie builders.
	Movie *MovieClient
	// OfflineDownload is the client for interacting with the OfflineDownload builders.
	OfflineDownload *OfflineDownloadClient
	// Setting is the client for interacting with the Setting builders.
	Setting *SettingClient
	// Subscription is the client for interacting with the Subscription builders.
	Subscription *SubscriptionClient
	// Subtitle is the client for interacting with the Subtitle builders.
	Subtitle *SubtitleClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// ViewedMovie is the client for interacting with the ViewedMovie builders.
	ViewedMovie *ViewedMovieClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Actor = NewActorClient(c.config)
	c.EmbyNotification = NewEmbyNotificationClient(c.config)
	c.File = NewFileClient(c.config)
	c.MetadataCache = NewMetadataCacheClient(c.config)
	c.Movie = NewMovieClient(c.config)
	c.OfflineDownload = NewOfflineDownloadClient(c.config)
	c.Setting = NewSettingClient(c.config)
	c.Subscription = NewSubscriptionClient(c.config)
	c.Subtitle = NewSubtitleClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.ViewedMovie = NewViewedMovieClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Actor:            NewActorClient(cfg),
		EmbyNotification: NewEmbyNotificationClient(cfg),
		File:             NewFileClient(cfg),
		MetadataCache:    NewMetadataCacheClient(cfg),
		Movie:            NewMovieClient(cfg),
		OfflineDownload:  NewOfflineDownloadClient(cfg),
		Setting:          NewSettingClient(cfg),
		Subscription:     NewSubscriptionClient(cfg),
		Subtitle:         NewSubtitleClient(cfg),
		Tag:              NewTagClient(cfg),
		Task:             NewTaskClient(cfg),
		ViewedMovie:      NewViewedMovieClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Actor:            NewActorClient(cfg),
		EmbyNotification: NewEmbyNotificationClient(cfg),
		File:             NewFileClient(cfg),
		MetadataCache:    NewMetadataCacheClient(cfg),
		Movie:            NewMovieClient(cfg),
		OfflineDownload:  NewOfflineDownloadClient(cfg),
		Setting:          NewSettingClient(cfg),
		Subscription:     NewSubscriptionClient(cfg),
		Subtitle:         NewSubtitleClient(cfg),
		Tag:              NewTagClient(cfg),
		Task:             NewTaskClient(cfg),
		ViewedMovie:      NewViewedMovieClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Actor.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Actor, c.EmbyNotification, c.File, c.MetadataCache, c.Movie,
		c.OfflineDownload, c.Setting, c.Subscription, c.Subtitle, c.Tag, c.Task,
		c.ViewedMovie,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Actor, c.EmbyNotification, c.File, c.MetadataCache, c.Movie,
		c.OfflineDownload, c.Setting, c.Subscription, c.Subtitle, c.Tag, c.Task,
		c.ViewedMovie,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActorMutation:
		return c.Actor.mutate(ctx, m)
	case *EmbyNotificationMutation:
		return c.EmbyNotification.mutate(ctx, m)
	case *FileMutation:
		return c.File.mutate(ctx, m)
	case *MetadataCacheMutation:
		return c.MetadataCache.mutate(ctx, m)
	case *MovieMutation:
		return c.Movie.mutate(ctx, m)
	case *OfflineDownloadMutation:
		return c.OfflineDownload.mutate(ctx, m)
	case *SettingMutation:
		return c.Setting.mutate(ctx, m)
	case *SubscriptionMutation:
		return c.Subscription.mutate(ctx, m)
	case *SubtitleMutation:
		return c.Subtitle.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *ViewedMovieMutation:
		return c.ViewedMovie.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActorClient is a client for the Actor schema.
type ActorClient struct {
	config
}

// NewActorClient returns a client for the Actor from the given config.
func NewActorClient(c config) *ActorClient {
	return &ActorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `actor.Hooks(f(g(h())))`.
func (c *ActorClient) Use(hooks ...Hook) {
	c.hooks.Actor = append(c.hooks.Actor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `actor.Intercept(f(g(h())))`.
func (c *ActorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Actor = append(c.inters.Actor, interceptors...)
}

// Create returns a builder for creating a Actor entity.
func (c *ActorClient) Create() *ActorCreate {
	mutation := newActorMutation(c.config, OpCreate)
	return &ActorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Actor entities.
func (c *ActorClient) CreateBulk(builders ...*ActorCreate) *ActorCreateBulk {
	return &ActorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActorClient) MapCreateBulk(slice any, setFunc func(*ActorCreate, int)) *ActorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActorCreateBulk{err: fmt.Errorf("calling to ActorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Actor.
func (c *ActorClient) Update() *ActorUpdate {
	mutation := newActorMutation(c.config, OpUpdate)
	return &ActorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActorClient) UpdateOne(_m *Actor) *ActorUpdateOne {
	mutation := newActorMutation(c.config, OpUpdateOne, withActor(_m))
	return &ActorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActorClient) UpdateOneID(id int) *ActorUpdateOne {
	mutation := newActorMutation(c.config, OpUpdateOne, withActorID(id))
	return &ActorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Actor.
func (c *ActorClient) Delete() *ActorDelete {
	mutation := newActorMutation(c.config, OpDelete)
	return &ActorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActorClient) DeleteOne(_m *Actor) *ActorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActorClient) DeleteOneID(id int) *ActorDeleteOne {
	builder := c.Delete().Where(actor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActorDeleteOne{builder}
}

// Query returns a query builder for Actor.
func (c *ActorClient) Query() *ActorQuery {
	return &ActorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActor},
		inters: c.Interceptors(),
	}
}

// Get returns a Actor entity by its id.
func (c *ActorClient) Get(ctx context.Context, id int) (*Actor, error) {
	return c.Query().Where(actor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActorClient) GetX(ctx context.Context, id int) *Actor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovies queries the movies edge of a Actor.
func (c *ActorClient) QueryMovies(_m *Actor) *MovieQuery {
	query := (&MovieClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actor.Table, actor.FieldID, id),
			sqlgraph.To(movie.Table, movie.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, actor.MoviesTable, actor.MoviesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActorClient) Hooks() []Hook {
	return c.hooks.Actor
}

// Interceptors returns the client interceptors.
func (c *ActorClient) Interceptors() []Interceptor {
	return c.inters.Actor
}

func (c *ActorClient) mutate(ctx context.Context, m *ActorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Actor mutation op: %q", m.Op())
	}
}

// EmbyNotificationClient is a client for the EmbyNotification schema.
type EmbyNotificationClient struct {
	config
}

// NewEmbyNotificationClient returns a client for the EmbyNotification from the given config.
func NewEmbyNotificationClient(c config) *EmbyNotificationClient {
	return &EmbyNotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `embynotification.Hooks(f(g(h())))`.
func (c *EmbyNotificationClient) Use(hooks ...Hook) {
	c.hooks.EmbyNotification = append(c.hooks.EmbyNotification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `embynotification.Intercept(f(g(h())))`.
func (c *EmbyNotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmbyNotification = append(c.inters.EmbyNotification, interceptors...)
}

// Create returns a builder for creating a EmbyNotification entity.
func (c *EmbyNotificationClient) Create() *EmbyNotificationCreate {
	mutation := newEmbyNotificationMutation(c.config, OpCreate)
	return &EmbyNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmbyNotification entities.
func (c *EmbyNotificationClient) CreateBulk(builders ...*EmbyNotificationCreate) *EmbyNotificationCreateBulk {
	return &EmbyNotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmbyNotificationClient) MapCreateBulk(slice any, setFunc func(*EmbyNotificationCreate, int)) *EmbyNotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmbyNotificationCreateBulk{err: fmt.Errorf("calling to EmbyNotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmbyNotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmbyNotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmbyNotification.
func (c *EmbyNotificationClient) Update() *EmbyNotificationUpdate {
	mutation := newEmbyNotificationMutation(c.config, OpUpdate)
	return &EmbyNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmbyNotificationClient) UpdateOne(_m *EmbyNotification) *EmbyNotificationUpdateOne {
	mutation := newEmbyNotificationMutation(c.config, OpUpdateOne, withEmbyNotification(_m))
	return &EmbyNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmbyNotificationClient) UpdateOneID(id int) *EmbyNotificationUpdateOne {
	mutation := newEmbyNotificationMutation(c.config, OpUpdateOne, withEmbyNotificationID(id))
	return &EmbyNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmbyNotification.
func (c *EmbyNotificationClient) Delete() *EmbyNotificationDelete {
	mutation := newEmbyNotificationMutation(c.config, OpDelete)
	return &EmbyNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmbyNotificationClient) DeleteOne(_m *EmbyNotification) *EmbyNotificationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmbyNotificationClient) DeleteOneID(id int) *EmbyNotificationDeleteOne {
	builder := c.Delete().Where(embynotification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmbyNotificationDeleteOne{builder}
}

// Query returns a query builder for EmbyNotification.
func (c *EmbyNotificationClient) Query() *EmbyNotificationQuery {
	return &EmbyNotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmbyNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a EmbyNotification entity by its id.
func (c *EmbyNotificationClient) Get(ctx context.Context, id int) (*EmbyNotification, error) {
	return c.Query().Where(embynotification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmbyNotificationClient) GetX(ctx context.Context, id int) *EmbyNotification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmbyNotificationClient) Hooks() []Hook {
	return c.hooks.EmbyNotification
}

// Interceptors returns the client interceptors.
func (c *EmbyNotificationClient) Interceptors() []Interceptor {
	return c.inters.EmbyNotification
}

func (c *EmbyNotificationClient) mutate(ctx context.Context, m *EmbyNotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmbyNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmbyNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmbyNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmbyNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmbyNotification mutation op: %q", m.Op())
	}
}

// FileClient is a client for the File schema.
type FileClient struct {
	config
}

// NewFileClient returns a client for the File from the given config.
func NewFileClient(c config) *FileClient {
	return &FileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `file.Hooks(f(g(h())))`.
func (c *FileClient) Use(hooks ...Hook) {
	c.hooks.File = append(c.hooks.File, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `file.Intercept(f(g(h())))`.
func (c *FileClient) Intercept(interceptors ...Interceptor) {
	c.inters.File = append(c.inters.File, interceptors...)
}

// Create returns a builder for creating a File entity.
func (c *FileClient) Create() *FileCreate {
	mutation := newFileMutation(c.config, OpCreate)
	return &FileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of File entities.
func (c *FileClient) CreateBulk(builders ...*FileCreate) *FileCreateBulk {
	return &FileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileClient) MapCreateBulk(slice any, setFunc func(*FileCreate, int)) *FileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileCreateBulk{err: fmt.Errorf("calling to FileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for File.
func (c *FileClient) Update() *FileUpdate {
	mutation := newFileMutation(c.config, OpUpdate)
	return &FileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileClient) UpdateOne(_m *File) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFile(_m))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileClient) UpdateOneID(id int) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFileID(id))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for File.
func (c *FileClient) Delete() *FileDelete {
	mutation := newFileMutation(c.config, OpDelete)
	return &FileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileClient) DeleteOne(_m *File) *FileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileClient) DeleteOneID(id int) *FileDeleteOne {
	builder := c.Delete().Where(file.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileDeleteOne{builder}
}

// Query returns a query builder for File.
func (c *FileClient) Query() *FileQuery {
	return &FileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFile},
		inters: c.Interceptors(),
	}
}

// Get returns a File entity by its id.
func (c *FileClient) Get(ctx context.Context, id int) (*File, error) {
	return c.Query().Where(file.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileClient) GetX(ctx context.Context, id int) *File {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovie queries the movie edge of a File.
func (c *FileClient) QueryMovie(_m *File) *MovieQuery {
	query := (&MovieClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(file.Table, file.FieldID, id),
			sqlgraph.To(movie.Table, movie.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, file.MovieTable, file.MovieColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FileClient) Hooks() []Hook {
	return c.hooks.File
}

// Interceptors returns the client interceptors.
func (c *FileClient) Interceptors() []Interceptor {
	return c.inters.File
}

func (c *FileClient) mutate(ctx context.Context, m *FileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown File mutation op: %q", m.Op())
	}
}

// MetadataCacheClient is a client for the MetadataCache schema.
type MetadataCacheClient struct {
	config
}

// NewMetadataCacheClient returns a client for the MetadataCache from the given config.
func NewMetadataCacheClient(c config) *MetadataCacheClient {
	return &MetadataCacheClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `metadatacache.Hooks(f(g(h())))`.
func (c *MetadataCacheClient) Use(hooks ...Hook) {
	c.hooks.MetadataCache = append(c.hooks.MetadataCache, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `metadatacache.Intercept(f(g(h())))`.
func (c *MetadataCacheClient) Intercept(interceptors ...Interceptor) {
	c.inters.MetadataCache = append(c.inters.MetadataCache, interceptors...)
}

// Create returns a builder for creating a MetadataCache entity.
func (c *MetadataCacheClient) Create() *MetadataCacheCreate {
	mutation := newMetadataCacheMutation(c.config, OpCreate)
	return &MetadataCacheCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MetadataCache entities.
func (c *MetadataCacheClient) CreateBulk(builders ...*MetadataCacheCreate) *MetadataCacheCreateBulk {
	return &MetadataCacheCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MetadataCacheClient) MapCreateBulk(slice any, setFunc func(*MetadataCacheCreate, int)) *MetadataCacheCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MetadataCacheCreateBulk{err: fmt.Errorf("calling to MetadataCacheClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MetadataCacheCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MetadataCacheCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MetadataCache.
func (c *MetadataCacheClient) Update() *MetadataCacheUpdate {
	mutation := newMetadataCacheMutation(c.config, OpUpdate)
	return &MetadataCacheUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MetadataCacheClient) UpdateOne(_m *MetadataCache) *MetadataCacheUpdateOne {
	mutation := newMetadataCacheMutation(c.config, OpUpdateOne, withMetadataCache(_m))
	return &MetadataCacheUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MetadataCacheClient) UpdateOneID(id int) *MetadataCacheUpdateOne {
	mutation := newMetadataCacheMutation(c.config, OpUpdateOne, withMetadataCacheID(id))
	return &MetadataCacheUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MetadataCache.
func (c *MetadataCacheClient) Delete() *MetadataCacheDelete {
	mutation := newMetadataCacheMutation(c.config, OpDelete)
	return &MetadataCacheDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MetadataCacheClient) DeleteOne(_m *MetadataCache) *MetadataCacheDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MetadataCacheClient) DeleteOneID(id int) *MetadataCacheDeleteOne {
	builder := c.Delete().Where(metadatacache.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MetadataCacheDeleteOne{builder}
}

// Query returns a query builder for MetadataCache.
func (c *MetadataCacheClient) Query() *MetadataCacheQuery {
	return &MetadataCacheQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMetadataCache},
		inters: c.Interceptors(),
	}
}

// Get returns a MetadataCache entity by its id.
func (c *MetadataCacheClient) Get(ctx context.Context, id int) (*MetadataCache, error) {
	return c.Query().Where(metadatacache.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MetadataCacheClient) GetX(ctx context.Context, id int) *MetadataCache {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MetadataCacheClient) Hooks() []Hook {
	return c.hooks.MetadataCache
}

// Interceptors returns the client interceptors.
func (c *MetadataCacheClient) Interceptors() []Interceptor {
	return c.inters.MetadataCache
}

func (c *MetadataCacheClient) mutate(ctx context.Context, m *MetadataCacheMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MetadataCacheCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MetadataCacheUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MetadataCacheUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MetadataCacheDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MetadataCache mutation op: %q", m.Op())
	}
}

// MovieClient is a client for the Movie schema.
type MovieClient struct {
	config
}

// NewMovieClient returns a client for the Movie from the given config.
func NewMovieClient(c config) *MovieClient {
	return &MovieClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `movie.Hooks(f(g(h())))`.
func (c *MovieClient) Use(hooks ...Hook) {
	c.hooks.Movie = append(c.hooks.Movie, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `movie.Intercept(f(g(h())))`.
func (c *MovieClient) Intercept(interceptors ...Interceptor) {
	c.inters.Movie = append(c.inters.Movie, interceptors...)
}

// Create returns a builder for creating a Movie entity.
func (c *MovieClient) Create() *MovieCreate {
	mutation := newMovieMutation(c.config, OpCreate)
	return &MovieCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Movie entities.
func (c *MovieClient) CreateBulk(builders ...*MovieCreate) *MovieCreateBulk {
	return &MovieCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MovieClient) MapCreateBulk(slice any, setFunc func(*MovieCreate, int)) *MovieCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MovieCreateBulk{err: fmt.Errorf("calling to MovieClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MovieCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MovieCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Movie.
func (c *MovieClient) Update() *MovieUpdate {
	mutation := newMovieMutation(c.config, OpUpdate)
	return &MovieUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MovieClient) UpdateOne(_m *Movie) *MovieUpdateOne {
	mutation := newMovieMutation(c.config, OpUpdateOne, withMovie(_m))
	return &MovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MovieClient) UpdateOneID(id int) *MovieUpdateOne {
	mutation := newMovieMutation(c.config, OpUpdateOne, withMovieID(id))
	return &MovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Movie.
func (c *MovieClient) Delete() *MovieDelete {
	mutation := newMovieMutation(c.config, OpDelete)
	return &MovieDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MovieClient) DeleteOne(_m *Movie) *MovieDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MovieClient) DeleteOneID(id int) *MovieDeleteOne {
	builder := c.Delete().Where(movie.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MovieDeleteOne{builder}
}

// Query returns a query builder for Movie.
func (c *MovieClient) Query() *MovieQuery {
	return &MovieQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMovie},
		inters: c.Interceptors(),
	}
}

// Get returns a Movie entity by its id.
func (c *MovieClient) Get(ctx context.Context, id int) (*Movie, error) {
	return c.Query().Where(movie.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MovieClient) GetX(ctx context.Context, id int) *Movie {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryActors queries the actors edge of a Movie.
func (c *MovieClient) QueryActors(_m *Movie) *ActorQuery {
	query := (&ActorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(movie.Table, movie.FieldID, id),
			sqlgraph.To(actor.Table, actor.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, movie.ActorsTable, movie.ActorsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Movie.
func (c *MovieClient) QueryTags(_m *Movie) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(movie.Table, movie.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, movie.TagsTable, movie.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFiles queries the files edge of a Movie.
func (c *MovieClient) QueryFiles(_m *Movie) *FileQuery {
	query := (&FileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(movie.Table, movie.FieldID, id),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, movie.FilesTable, movie.FilesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySubtitles queries the subtitles edge of a Movie.
func (c *MovieClient) QuerySubtitles(_m *Movie) *SubtitleQuery {
	query := (&SubtitleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(movie.Table, movie.FieldID, id),
			sqlgraph.To(subtitle.Table, subtitle.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, movie.SubtitlesTable, movie.SubtitlesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MovieClient) Hooks() []Hook {
	hooks := c.hooks.Movie
	return append(hooks[:len(hooks):len(hooks)], movie.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *MovieClient) Interceptors() []Interceptor {
	return c.inters.Movie
}

func (c *MovieClient) mutate(ctx context.Context, m *MovieMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MovieCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MovieUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MovieDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Movie mutation op: %q", m.Op())
	}
}

// OfflineDownloadClient is a client for the OfflineDownload schema.
type OfflineDownloadClient struct {
	config
}

// NewOfflineDownloadClient returns a client for the OfflineDownload from the given config.
func NewOfflineDownloadClient(c config) *OfflineDownloadClient {
	return &OfflineDownloadClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `offlinedownload.Hooks(f(g(h())))`.
func (c *OfflineDownloadClient) Use(hooks ...Hook) {
	c.hooks.OfflineDownload = append(c.hooks.OfflineDownload, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `offlinedownload.Intercept(f(g(h())))`.
func (c *OfflineDownloadClient) Intercept(interceptors ...Interceptor) {
	c.inters.OfflineDownload = append(c.inters.OfflineDownload, interceptors...)
}

// Create returns a builder for creating a OfflineDownload entity.
func (c *OfflineDownloadClient) Create() *OfflineDownloadCreate {
	mutation := newOfflineDownloadMutation(c.config, OpCreate)
	return &OfflineDownloadCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OfflineDownload entities.
func (c *OfflineDownloadClient) CreateBulk(builders ...*OfflineDownloadCreate) *OfflineDownloadCreateBulk {
	return &OfflineDownloadCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OfflineDownloadClient) MapCreateBulk(slice any, setFunc func(*OfflineDownloadCreate, int)) *OfflineDownloadCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OfflineDownloadCreateBulk{err: fmt.Errorf("calling to OfflineDownloadClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OfflineDownloadCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OfflineDownloadCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OfflineDownload.
func (c *OfflineDownloadClient) Update() *OfflineDownloadUpdate {
	mutation := newOfflineDownloadMutation(c.config, OpUpdate)
	return &OfflineDownloadUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OfflineDownloadClient) UpdateOne(_m *OfflineDownload) *OfflineDownloadUpdateOne {
	mutation := newOfflineDownloadMutation(c.config, OpUpdateOne, withOfflineDownload(_m))
	return &OfflineDownloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OfflineDownloadClient) UpdateOneID(id int) *OfflineDownloadUpdateOne {
	mutation := newOfflineDownloadMutation(c.config, OpUpdateOne, withOfflineDownloadID(id))
	return &OfflineDownloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OfflineDownload.
func (c *OfflineDownloadClient) Delete() *OfflineDownloadDelete {
	mutation := newOfflineDownloadMutation(c.config, OpDelete)
	return &OfflineDownloadDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OfflineDownloadClient) DeleteOne(_m *OfflineDownload) *OfflineDownloadDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OfflineDownloadClient) DeleteOneID(id int) *OfflineDownloadDeleteOne {
	builder := c.Delete().Where(offlinedownload.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OfflineDownloadDeleteOne{builder}
}

// Query returns a query builder for OfflineDownload.
func (c *OfflineDownloadClient) Query() *OfflineDownloadQuery {
	return &OfflineDownloadQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOfflineDownload},
		inters: c.Interceptors(),
	}
}

// Get returns a OfflineDownload entity by its id.
func (c *OfflineDownloadClient) Get(ctx context.Context, id int) (*OfflineDownload, error) {
	return c.Query().Where(offlinedownload.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OfflineDownloadClient) GetX(ctx context.Context, id int) *OfflineDownload {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OfflineDownloadClient) Hooks() []Hook {
	return c.hooks.OfflineDownload
}

// Interceptors returns the client interceptors.
func (c *OfflineDownloadClient) Interceptors() []Interceptor {
	return c.inters.OfflineDownload
}

func (c *OfflineDownloadClient) mutate(ctx context.Context, m *OfflineDownloadMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OfflineDownloadCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OfflineDownloadUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OfflineDownloadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OfflineDownloadDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OfflineDownload mutation op: %q", m.Op())
	}
}

// SettingClient is a client for the Setting schema.
type SettingClient struct {
	config
}

// NewSettingClient returns a client for the Setting from the given config.
func NewSettingClient(c config) *SettingClient {
	return &SettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `setting.Hooks(f(g(h())))`.
func (c *SettingClient) Use(hooks ...Hook) {
	c.hooks.Setting = append(c.hooks.Setting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `setting.Intercept(f(g(h())))`.
func (c *SettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Setting = append(c.inters.Setting, interceptors...)
}

// Create returns a builder for creating a Setting entity.
func (c *SettingClient) Create() *SettingCreate {
	mutation := newSettingMutation(c.config, OpCreate)
	return &SettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Setting entities.
func (c *SettingClient) CreateBulk(builders ...*SettingCreate) *SettingCreateBulk {
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingClient) MapCreateBulk(slice any, setFunc func(*SettingCreate, int)) *SettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingCreateBulk{err: fmt.Errorf("calling to SettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Setting.
func (c *SettingClient) Update() *SettingUpdate {
	mutation := newSettingMutation(c.config, OpUpdate)
	return &SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingClient) UpdateOne(_m *Setting) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSetting(_m))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingClient) UpdateOneID(id int) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSettingID(id))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Setting.
func (c *SettingClient) Delete() *SettingDelete {
	mutation := newSettingMutation(c.config, OpDelete)
	return &SettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingClient) DeleteOne(_m *Setting) *SettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingClient) DeleteOneID(id int) *SettingDeleteOne {
	builder := c.Delete().Where(setting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingDeleteOne{builder}
}

// Query returns a query builder for Setting.
func (c *SettingClient) Query() *SettingQuery {
	return &SettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a Setting entity by its id.
func (c *SettingClient) Get(ctx context.Context, id int) (*Setting, error) {
	return c.Query().Where(setting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingClient) GetX(ctx context.Context, id int) *Setting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingClient) Hooks() []Hook {
	return c.hooks.Setting
}

// Interceptors returns the client interceptors.
func (c *SettingClient) Interceptors() []Interceptor {
	return c.inters.Setting
}

func (c *SettingClient) mutate(ctx context.Context, m *SettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Setting mutation op: %q", m.Op())
	}
}

// SubscriptionClient is a client for the Subscription schema.
type SubscriptionClient struct {
	config
}

// NewSubscriptionClient returns a client for the Subscription from the given config.
func NewSubscriptionClient(c config) *SubscriptionClient {
	return &SubscriptionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `subscription.Hooks(f(g(h())))`.
func (c *SubscriptionClient) Use(hooks ...Hook) {
	c.hooks.Subscription = append(c.hooks.Subscription, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `subscription.Intercept(f(g(h())))`.
func (c *SubscriptionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Subscription = append(c.inters.Subscription, interceptors...)
}

// Create returns a builder for creating a Subscription entity.
func (c *SubscriptionClient) Create() *SubscriptionCreate {
	mutation := newSubscriptionMutation(c.config, OpCreate)
	return &SubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Subscription entities.
func (c *SubscriptionClient) CreateBulk(builders ...*SubscriptionCreate) *SubscriptionCreateBulk {
	return &SubscriptionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SubscriptionClient) MapCreateBulk(slice any, setFunc func(*SubscriptionCreate, int)) *SubscriptionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SubscriptionCreateBulk{err: fmt.Errorf("calling to SubscriptionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SubscriptionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SubscriptionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Subscription.
func (c *SubscriptionClient) Update() *SubscriptionUpdate {
	mutation := newSubscriptionMutation(c.config, OpUpdate)
	return &SubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SubscriptionClient) UpdateOne(_m *Subscription) *SubscriptionUpdateOne {
	mutation := newSubscriptionMutation(c.config, OpUpdateOne, withSubscription(_m))
	return &SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SubscriptionClient) UpdateOneID(id int) *SubscriptionUpdateOne {
	mutation := newSubscriptionMutation(c.config, OpUpdateOne, withSubscriptionID(id))
	return &SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Subscription.
func (c *SubscriptionClient) Delete() *SubscriptionDelete {
	mutation := newSubscriptionMutation(c.config, OpDelete)
	return &SubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SubscriptionClient) DeleteOne(_m *Subscription) *SubscriptionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SubscriptionClient) DeleteOneID(id int) *SubscriptionDeleteOne {
	builder := c.Delete().Where(subscription.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SubscriptionDeleteOne{builder}
}

// Query returns a query builder for Subscription.
func (c *SubscriptionClient) Query() *SubscriptionQuery {
	return &SubscriptionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSubscription},
		inters: c.Interceptors(),
	}
}

// Get returns a Subscription entity by its id.
func (c *SubscriptionClient) Get(ctx context.Context, id int) (*Subscription, error) {
	return c.Query().Where(subscription.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SubscriptionClient) GetX(ctx context.Context, id int) *Subscription {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SubscriptionClient) Hooks() []Hook {
	return c.hooks.Subscription
}

// Interceptors returns the client interceptors.
func (c *SubscriptionClient) Interceptors() []Interceptor {
	return c.inters.Subscription
}

func (c *SubscriptionClient) mutate(ctx context.Context, m *SubscriptionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SubscriptionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SubscriptionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SubscriptionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SubscriptionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Subscription mutation op: %q", m.Op())
	}
}

// SubtitleClient is a client for the Subtitle schema.
type SubtitleClient struct {
	config
}

// NewSubtitleClient returns a client for the Subtitle from the given config.
func NewSubtitleClient(c config) *SubtitleClient {
	return &SubtitleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `subtitle.Hooks(f(g(h())))`.
func (c *SubtitleClient) Use(hooks ...Hook) {
	c.hooks.Subtitle = append(c.hooks.Subtitle, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `subtitle.Intercept(f(g(h())))`.
func (c *SubtitleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Subtitle = append(c.inters.Subtitle, interceptors...)
}

// Create returns a builder for creating a Subtitle entity.
func (c *SubtitleClient) Create() *SubtitleCreate {
	mutation := newSubtitleMutation(c.config, OpCreate)
	return &SubtitleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Subtitle entities.
func (c *SubtitleClient) CreateBulk(builders ...*SubtitleCreate) *SubtitleCreateBulk {
	return &SubtitleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SubtitleClient) MapCreateBulk(slice any, setFunc func(*SubtitleCreate, int)) *SubtitleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SubtitleCreateBulk{err: fmt.Errorf("calling to SubtitleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SubtitleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SubtitleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Subtitle.
func (c *SubtitleClient) Update() *SubtitleUpdate {
	mutation := newSubtitleMutation(c.config, OpUpdate)
	return &SubtitleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SubtitleClient) UpdateOne(_m *Subtitle) *SubtitleUpdateOne {
	mutation := newSubtitleMutation(c.config, OpUpdateOne, withSubtitle(_m))
	return &SubtitleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SubtitleClient) UpdateOneID(id int) *SubtitleUpdateOne {
	mutation := newSubtitleMutation(c.config, OpUpdateOne, withSubtitleID(id))
	return &SubtitleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Subtitle.
func (c *SubtitleClient) Delete() *SubtitleDelete {
	mutation := newSubtitleMutation(c.config, OpDelete)
	return &SubtitleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SubtitleClient) DeleteOne(_m *Subtitle) *SubtitleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SubtitleClient) DeleteOneID(id int) *SubtitleDeleteOne {
	builder := c.Delete().Where(subtitle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SubtitleDeleteOne{builder}
}

// Query returns a query builder for Subtitle.
func (c *SubtitleClient) Query() *SubtitleQuery {
	return &SubtitleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSubtitle},
		inters: c.Interceptors(),
	}
}

// Get returns a Subtitle entity by its id.
func (c *SubtitleClient) Get(ctx context.Context, id int) (*Subtitle, error) {
	return c.Query().Where(subtitle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SubtitleClient) GetX(ctx context.Context, id int) *Subtitle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovie queries the movie edge of a Subtitle.
func (c *SubtitleClient) QueryMovie(_m *Subtitle) *MovieQuery {
	query := (&MovieClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(subtitle.Table, subtitle.FieldID, id),
			sqlgraph.To(movie.Table, movie.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subtitle.MovieTable, subtitle.MovieColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SubtitleClient) Hooks() []Hook {
	return c.hooks.Subtitle
}

// Interceptors returns the client interceptors.
func (c *SubtitleClient) Interceptors() []Interceptor {
	return c.inters.Subtitle
}

func (c *SubtitleClient) mutate(ctx context.Context, m *SubtitleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SubtitleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SubtitleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SubtitleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SubtitleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Subtitle mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id int) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMovies queries the movies edge of a Tag.
func (c *TagClient) QueryMovies(_m *Tag) *MovieQuery {
	query := (&MovieClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(movie.Table, movie.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.MoviesTable, tag.MoviesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id int) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id int) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id int) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id int) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// ViewedMovieClient is a client for the ViewedMovie schema.
type ViewedMovieClient struct {
	config
}

// NewViewedMovieClient returns a client for the ViewedMovie from the given config.
func NewViewedMovieClient(c config) *ViewedMovieClient {
	return &ViewedMovieClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `viewedmovie.Hooks(f(g(h())))`.
func (c *ViewedMovieClient) Use(hooks ...Hook) {
	c.hooks.ViewedMovie = append(c.hooks.ViewedMovie, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `viewedmovie.Intercept(f(g(h())))`.
func (c *ViewedMovieClient) Intercept(interceptors ...Interceptor) {
	c.inters.ViewedMovie = append(c.inters.ViewedMovie, interceptors...)
}

// Create returns a builder for creating a ViewedMovie entity.
func (c *ViewedMovieClient) Create() *ViewedMovieCreate {
	mutation := newViewedMovieMutation(c.config, OpCreate)
	return &ViewedMovieCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ViewedMovie entities.
func (c *ViewedMovieClient) CreateBulk(builders ...*ViewedMovieCreate) *ViewedMovieCreateBulk {
	return &ViewedMovieCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ViewedMovieClient) MapCreateBulk(slice any, setFunc func(*ViewedMovieCreate, int)) *ViewedMovieCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ViewedMovieCreateBulk{err: fmt.Errorf("calling to ViewedMovieClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ViewedMovieCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ViewedMovieCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ViewedMovie.
func (c *ViewedMovieClient) Update() *ViewedMovieUpdate {
	mutation := newViewedMovieMutation(c.config, OpUpdate)
	return &ViewedMovieUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ViewedMovieClient) UpdateOne(_m *ViewedMovie) *ViewedMovieUpdateOne {
	mutation := newViewedMovieMutation(c.config, OpUpdateOne, withViewedMovie(_m))
	return &ViewedMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ViewedMovieClient) UpdateOneID(id int) *ViewedMovieUpdateOne {
	mutation := newViewedMovieMutation(c.config, OpUpdateOne, withViewedMovieID(id))
	return &ViewedMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ViewedMovie.
func (c *ViewedMovieClient) Delete() *ViewedMovieDelete {
	mutation := newViewedMovieMutation(c.config, OpDelete)
	return &ViewedMovieDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ViewedMovieClient) DeleteOne(_m *ViewedMovie) *ViewedMovieDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ViewedMovieClient) DeleteOneID(id int) *ViewedMovieDeleteOne {
	builder := c.Delete().Where(viewedmovie.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ViewedMovieDeleteOne{builder}
}

// Query returns a query builder for ViewedMovie.
func (c *ViewedMovieClient) Query() *ViewedMovieQuery {
	return &ViewedMovieQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeViewedMovie},
		inters: c.Interceptors(),
	}
}

// Get returns a ViewedMovie entity by its id.
func (c *ViewedMovieClient) Get(ctx context.Context, id int) (*ViewedMovie, error) {
	return c.Query().Where(viewedmovie.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ViewedMovieClient) GetX(ctx context.Context, id int) *ViewedMovie {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ViewedMovieClient) Hooks() []Hook {
	return c.hooks.ViewedMovie
}

// Interceptors returns the client interceptors.
func (c *ViewedMovieClient) Interceptors() []Interceptor {
	return c.inters.ViewedMovie
}

func (c *ViewedMovieClient) mutate(ctx context.Context, m *ViewedMovieMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ViewedMovieCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ViewedMovieUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ViewedMovieUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ViewedMovieDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ViewedMovie mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Actor, EmbyNotification, File, MetadataCache, Movie, OfflineDownload, Setting,
		Subscription, Subtitle, Tag, Task, ViewedMovie []ent.Hook
	}
	inters struct {
		Actor, EmbyNotification, File, MetadataCache, Movie, OfflineDownload, Setting,
		Subscription, Subtitle, Tag, Task, ViewedMovie []ent.Interceptor
	}
)
