// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/domain"
	"github.com/ppxb/miyabi/internal/ent/metadatacache"
)

// MetadataCacheCreate is the builder for creating a MetadataCache entity.
type MetadataCacheCreate struct {
	config
	mutation *MetadataCacheMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *MetadataCacheCreate) SetProvider(v string) *MetadataCacheCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *MetadataCacheCreate) SetCode(v string) *MetadataCacheCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *MetadataCacheCreate) SetResult(v *domain.MovieMetadata) *MetadataCacheCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MetadataCacheCreate) SetExpiresAt(v time.Time) *MetadataCacheCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the MetadataCacheMutation object of the builder.
func (_c *MetadataCacheCreate) Mutation() *MetadataCacheMutation {
	return _c.mutation
}

// Save creates the MetadataCache in the database.
func (_c *MetadataCacheCreate) Save(ctx context.Context) (*MetadataCache, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MetadataCacheCreate) SaveX(ctx context.Context) *MetadataCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetadataCacheCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetadataCacheCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MetadataCacheCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "MetadataCache.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := metadatacache.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "MetadataCache.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "MetadataCache.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := metadatacache.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "MetadataCache.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MetadataCache.expires_at"`)}
	}
	return nil
}

func (_c *MetadataCacheCreate) sqlSave(ctx context.Context) (*MetadataCache, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MetadataCacheCreate) createSpec() (*MetadataCache, *sqlgraph.CreateSpec) {
	var (
		_node = &MetadataCache{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(metadatacache.Table, sqlgraph.NewFieldSpec(metadatacache.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(metadatacache.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(metadatacache.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(metadatacache.FieldResult, field.TypeJSON, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(metadatacache.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetadataCache.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetadataCacheUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *MetadataCacheCreate) OnConflict(opts ...sql.ConflictOption) *MetadataCacheUpsertOne {
	_c.conflict = opts
	return &MetadataCacheUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MetadataCacheCreate) OnConflictColumns(columns ...string) *MetadataCacheUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MetadataCacheUpsertOne{
		create: _c,
	}
}

type (
	// MetadataCacheUpsertOne is the builder for "upsert"-ing
	//  one MetadataCache node.
	MetadataCacheUpsertOne struct {
		create *MetadataCacheCreate
	}

	// MetadataCacheUpsert is the "OnConflict" setter.
	MetadataCacheUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *MetadataCacheUpsert) SetProvider(v string) *MetadataCacheUpsert {
	u.Set(metadatacache.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MetadataCacheUpsert) UpdateProvider() *MetadataCacheUpsert {
	u.SetExcluded(metadatacache.FieldProvider)
	return u
}

// SetCode sets the "code" field.
func (u *MetadataCacheUpsert) SetCode(v string) *MetadataCacheUpsert {
	u.Set(metadatacache.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MetadataCacheUpsert) UpdateCode() *MetadataCacheUpsert {
	u.SetExcluded(metadatacache.FieldCode)
	return u
}

// SetResult sets the "result" field.
func (u *MetadataCacheUpsert) SetResult(v *domain.MovieMetadata) *MetadataCacheUpsert {
	u.Set(metadatacache.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MetadataCacheUpsert) UpdateResult() *MetadataCacheUpsert {
	u.SetExcluded(metadatacache.FieldResult)
	return u
}

// ClearResult clears the value of the "result" field.
func (u *MetadataCacheUpsert) ClearResult() *MetadataCacheUpsert {
	u.SetNull(metadatacache.FieldResult)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *MetadataCacheUpsert) SetExpiresAt(v time.Time) *MetadataCacheUpsert {
	u.Set(metadatacache.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MetadataCacheUpsert) UpdateExpiresAt() *MetadataCacheUpsert {
	u.SetExcluded(metadatacache.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetadataCacheUpsertOne) UpdateNewValues() *MetadataCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MetadataCacheUpsertOne) Ignore() *MetadataCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetadataCacheUpsertOne) DoNothing() *MetadataCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetadataCacheCreate.OnConflict
// documentation for more info.
func (u *MetadataCacheUpsertOne) Update(set func(*MetadataCacheUpsert)) *MetadataCacheUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetadataCacheUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *MetadataCacheUpsertOne) SetProvider(v string) *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MetadataCacheUpsertOne) UpdateProvider() *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateProvider()
	})
}

// SetCode sets the "code" field.
func (u *MetadataCacheUpsertOne) SetCode(v string) *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MetadataCacheUpsertOne) UpdateCode() *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateCode()
	})
}

// SetResult sets the "result" field.
func (u *MetadataCacheUpsertOne) SetResult(v *domain.MovieMetadata) *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MetadataCacheUpsertOne) UpdateResult() *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *MetadataCacheUpsertOne) ClearResult() *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.ClearResult()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MetadataCacheUpsertOne) SetExpiresAt(v time.Time) *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MetadataCacheUpsertOne) UpdateExpiresAt() *MetadataCacheUpsertOne {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *MetadataCacheUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetadataCacheCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetadataCacheUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MetadataCacheUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MetadataCacheUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MetadataCacheCreateBulk is the builder for creating many MetadataCache entities in bulk.
type MetadataCacheCreateBulk struct {
	config
	err      error
	builders []*MetadataCacheCreate
	conflict []sql.ConflictOption
}

// Save creates the MetadataCache entities in the database.
func (_c *MetadataCacheCreateBulk) Save(ctx context.Context) ([]*MetadataCache, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MetadataCache, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MetadataCacheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MetadataCacheCreateBulk) SaveX(ctx context.Context) []*MetadataCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetadataCacheCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetadataCacheCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MetadataCache.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MetadataCacheUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *MetadataCacheCreateBulk) OnConflict(opts ...sql.ConflictOption) *MetadataCacheUpsertBulk {
	_c.conflict = opts
	return &MetadataCacheUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MetadataCacheCreateBulk) OnConflictColumns(columns ...string) *MetadataCacheUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MetadataCacheUpsertBulk{
		create: _c,
	}
}

// MetadataCacheUpsertBulk is the builder for "upsert"-ing
// a bulk of MetadataCache nodes.
type MetadataCacheUpsertBulk struct {
	create *MetadataCacheCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MetadataCacheUpsertBulk) UpdateNewValues() *MetadataCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MetadataCache.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MetadataCacheUpsertBulk) Ignore() *MetadataCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MetadataCacheUpsertBulk) DoNothing() *MetadataCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MetadataCacheCreateBulk.OnConflict
// documentation for more info.
func (u *MetadataCacheUpsertBulk) Update(set func(*MetadataCacheUpsert)) *MetadataCacheUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MetadataCacheUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *MetadataCacheUpsertBulk) SetProvider(v string) *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MetadataCacheUpsertBulk) UpdateProvider() *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateProvider()
	})
}

// SetCode sets the "code" field.
func (u *MetadataCacheUpsertBulk) SetCode(v string) *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MetadataCacheUpsertBulk) UpdateCode() *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateCode()
	})
}

// SetResult sets the "result" field.
func (u *MetadataCacheUpsertBulk) SetResult(v *domain.MovieMetadata) *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MetadataCacheUpsertBulk) UpdateResult() *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *MetadataCacheUpsertBulk) ClearResult() *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.ClearResult()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MetadataCacheUpsertBulk) SetExpiresAt(v time.Time) *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MetadataCacheUpsertBulk) UpdateExpiresAt() *MetadataCacheUpsertBulk {
	return u.Update(func(s *MetadataCacheUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *MetadataCacheUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MetadataCacheCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MetadataCacheCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MetadataCacheUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
