// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/domain"
	"github.com/ppxb/miyabi/internal/ent/actor"
	"github.com/ppxb/miyabi/internal/ent/file"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/predicate"
	"github.com/ppxb/miyabi/internal/ent/subtitle"
	"github.com/ppxb/miyabi/internal/ent/tag"
	"github.com/ppxb/miyabi/internal/nfo"
)

// MovieUpdate is the builder for updating Movie entities.
type MovieUpdate struct {
	config
	hooks    []Hook
	mutation *MovieMutation
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdate) Where(ps ...predicate.Movie) *MovieUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MovieUpdate) SetUpdatedAt(v time.Time) *MovieUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *MovieUpdate) SetCode(v string) *MovieUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableCode(v *string) *MovieUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetManualCode sets the "manual_code" field.
func (_u *MovieUpdate) SetManualCode(v string) *MovieUpdate {
	_u.mutation.SetManualCode(v)
	return _u
}

// SetNillableManualCode sets the "manual_code" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableManualCode(v *string) *MovieUpdate {
	if v != nil {
		_u.SetManualCode(*v)
	}
	return _u
}

// SetCanonicalCode sets the "canonical_code" field.
func (_u *MovieUpdate) SetCanonicalCode(v string) *MovieUpdate {
	_u.mutation.SetCanonicalCode(v)
	return _u
}

// SetNillableCanonicalCode sets the "canonical_code" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableCanonicalCode(v *string) *MovieUpdate {
	if v != nil {
		_u.SetCanonicalCode(*v)
	}
	return _u
}

// SetJavdbID sets the "javdb_id" field.
func (_u *MovieUpdate) SetJavdbID(v string) *MovieUpdate {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableJavdbID(v *string) *MovieUpdate {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// ClearJavdbID clears the value of the "javdb_id" field.
func (_u *MovieUpdate) ClearJavdbID() *MovieUpdate {
	_u.mutation.ClearJavdbID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *MovieUpdate) SetTitle(v string) *MovieUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableTitle(v *string) *MovieUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MovieUpdate) SetReleaseDate(v time.Time) *MovieUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableReleaseDate(v *time.Time) *MovieUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *MovieUpdate) ClearReleaseDate() *MovieUpdate {
	_u.mutation.ClearReleaseDate()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *MovieUpdate) SetDuration(v int) *MovieUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDuration(v *int) *MovieUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *MovieUpdate) AddDuration(v int) *MovieUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *MovieUpdate) ClearDuration() *MovieUpdate {
	_u.mutation.ClearDuration()
	return _u
}

// SetDirectorID sets the "director_id" field.
func (_u *MovieUpdate) SetDirectorID(v string) *MovieUpdate {
	_u.mutation.SetDirectorID(v)
	return _u
}

// SetNillableDirectorID sets the "director_id" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDirectorID(v *string) *MovieUpdate {
	if v != nil {
		_u.SetDirectorID(*v)
	}
	return _u
}

// ClearDirectorID clears the value of the "director_id" field.
func (_u *MovieUpdate) ClearDirectorID() *MovieUpdate {
	_u.mutation.ClearDirectorID()
	return _u
}

// SetDirectorName sets the "director_name" field.
func (_u *MovieUpdate) SetDirectorName(v string) *MovieUpdate {
	_u.mutation.SetDirectorName(v)
	return _u
}

// SetNillableDirectorName sets the "director_name" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableDirectorName(v *string) *MovieUpdate {
	if v != nil {
		_u.SetDirectorName(*v)
	}
	return _u
}

// ClearDirectorName clears the value of the "director_name" field.
func (_u *MovieUpdate) ClearDirectorName() *MovieUpdate {
	_u.mutation.ClearDirectorName()
	return _u
}

// SetMakerID sets the "maker_id" field.
func (_u *MovieUpdate) SetMakerID(v string) *MovieUpdate {
	_u.mutation.SetMakerID(v)
	return _u
}

// SetNillableMakerID sets the "maker_id" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableMakerID(v *string) *MovieUpdate {
	if v != nil {
		_u.SetMakerID(*v)
	}
	return _u
}

// ClearMakerID clears the value of the "maker_id" field.
func (_u *MovieUpdate) ClearMakerID() *MovieUpdate {
	_u.mutation.ClearMakerID()
	return _u
}

// SetMakerName sets the "maker_name" field.
func (_u *MovieUpdate) SetMakerName(v string) *MovieUpdate {
	_u.mutation.SetMakerName(v)
	return _u
}

// SetNillableMakerName sets the "maker_name" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableMakerName(v *string) *MovieUpdate {
	if v != nil {
		_u.SetMakerName(*v)
	}
	return _u
}

// ClearMakerName clears the value of the "maker_name" field.
func (_u *MovieUpdate) ClearMakerName() *MovieUpdate {
	_u.mutation.ClearMakerName()
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *MovieUpdate) SetSeriesID(v string) *MovieUpdate {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableSeriesID(v *string) *MovieUpdate {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// ClearSeriesID clears the value of the "series_id" field.
func (_u *MovieUpdate) ClearSeriesID() *MovieUpdate {
	_u.mutation.ClearSeriesID()
	return _u
}

// SetSeriesName sets the "series_name" field.
func (_u *MovieUpdate) SetSeriesName(v string) *MovieUpdate {
	_u.mutation.SetSeriesName(v)
	return _u
}

// SetNillableSeriesName sets the "series_name" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableSeriesName(v *string) *MovieUpdate {
	if v != nil {
		_u.SetSeriesName(*v)
	}
	return _u
}

// ClearSeriesName clears the value of the "series_name" field.
func (_u *MovieUpdate) ClearSeriesName() *MovieUpdate {
	_u.mutation.ClearSeriesName()
	return _u
}

// SetRating sets the "rating" field.
func (_u *MovieUpdate) SetRating(v float64) *MovieUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableRating(v *float64) *MovieUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *MovieUpdate) AddRating(v float64) *MovieUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *MovieUpdate) ClearRating() *MovieUpdate {
	_u.mutation.ClearRating()
	return _u
}

// SetCover sets the "cover" field.
func (_u *MovieUpdate) SetCover(v string) *MovieUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableCover(v *string) *MovieUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *MovieUpdate) ClearCover() *MovieUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetPoster sets the "poster" field.
func (_u *MovieUpdate) SetPoster(v string) *MovieUpdate {
	_u.mutation.SetPoster(v)
	return _u
}

// SetNillablePoster sets the "poster" field if the given value is not nil.
func (_u *MovieUpdate) SetNillablePoster(v *string) *MovieUpdate {
	if v != nil {
		_u.SetPoster(*v)
	}
	return _u
}

// ClearPoster clears the value of the "poster" field.
func (_u *MovieUpdate) ClearPoster() *MovieUpdate {
	_u.mutation.ClearPoster()
	return _u
}

// SetFanarts sets the "fanarts" field.
func (_u *MovieUpdate) SetFanarts(v []string) *MovieUpdate {
	_u.mutation.SetFanarts(v)
	return _u
}

// AppendFanarts appends value to the "fanarts" field.
func (_u *MovieUpdate) AppendFanarts(v []string) *MovieUpdate {
	_u.mutation.AppendFanarts(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MovieUpdate) SetMetadata(v *nfo.Movie) *MovieUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MovieUpdate) ClearMetadata() *MovieUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetMetadataSnapshot sets the "metadata_snapshot" field.
func (_u *MovieUpdate) SetMetadataSnapshot(v *domain.MetadataSnapshot) *MovieUpdate {
	_u.mutation.SetMetadataSnapshot(v)
	return _u
}

// ClearMetadataSnapshot clears the value of the "metadata_snapshot" field.
func (_u *MovieUpdate) ClearMetadataSnapshot() *MovieUpdate {
	_u.mutation.ClearMetadataSnapshot()
	return _u
}

// SetScrapeStatus sets the "scrape_status" field.
func (_u *MovieUpdate) SetScrapeStatus(v movie.ScrapeStatus) *MovieUpdate {
	_u.mutation.SetScrapeStatus(v)
	return _u
}

// SetNillableScrapeStatus sets the "scrape_status" field if the given value is not nil.
func (_u *MovieUpdate) SetNillableScrapeStatus(v *movie.ScrapeStatus) *MovieUpdate {
	if v != nil {
		_u.SetScrapeStatus(*v)
	}
	return _u
}

// AddActorIDs adds the "actors" edge to the Actor entity by IDs.
func (_u *MovieUpdate) AddActorIDs(ids ...int) *MovieUpdate {
	_u.mutation.AddActorIDs(ids...)
	return _u
}

// AddActors adds the "actors" edges to the Actor entity.
func (_u *MovieUpdate) AddActors(v ...*Actor) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActorIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *MovieUpdate) AddTagIDs(ids ...int) *MovieUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *MovieUpdate) AddTags(v ...*Tag) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *MovieUpdate) AddFileIDs(ids ...int) *MovieUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *MovieUpdate) AddFiles(v ...*File) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// AddSubtitleIDs adds the "subtitles" edge to the Subtitle entity by IDs.
func (_u *MovieUpdate) AddSubtitleIDs(ids ...int) *MovieUpdate {
	_u.mutation.AddSubtitleIDs(ids...)
	return _u
}

// AddSubtitles adds the "subtitles" edges to the Subtitle entity.
func (_u *MovieUpdate) AddSubtitles(v ...*Subtitle) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubtitleIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdate) Mutation() *MovieMutation {
	return _u.mutation
}

// ClearActors clears all "actors" edges to the Actor entity.
func (_u *MovieUpdate) ClearActors() *MovieUpdate {
	_u.mutation.ClearActors()
	return _u
}

// RemoveActorIDs removes the "actors" edge to Actor entities by IDs.
func (_u *MovieUpdate) RemoveActorIDs(ids ...int) *MovieUpdate {
	_u.mutation.RemoveActorIDs(ids...)
	return _u
}

// RemoveActors removes "actors" edges to Actor entities.
func (_u *MovieUpdate) RemoveActors(v ...*Actor) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActorIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *MovieUpdate) ClearTags() *MovieUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *MovieUpdate) RemoveTagIDs(ids ...int) *MovieUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *MovieUpdate) RemoveTags(v ...*Tag) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *MovieUpdate) ClearFiles() *MovieUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *MovieUpdate) RemoveFileIDs(ids ...int) *MovieUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *MovieUpdate) RemoveFiles(v ...*File) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// ClearSubtitles clears all "subtitles" edges to the Subtitle entity.
func (_u *MovieUpdate) ClearSubtitles() *MovieUpdate {
	_u.mutation.ClearSubtitles()
	return _u
}

// RemoveSubtitleIDs removes the "subtitles" edge to Subtitle entities by IDs.
func (_u *MovieUpdate) RemoveSubtitleIDs(ids ...int) *MovieUpdate {
	_u.mutation.RemoveSubtitleIDs(ids...)
	return _u
}

// RemoveSubtitles removes "subtitles" edges to Subtitle entities.
func (_u *MovieUpdate) RemoveSubtitles(v ...*Subtitle) *MovieUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubtitleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MovieUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MovieUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MovieUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if movie.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized movie.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := movie.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := movie.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Movie.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScrapeStatus(); ok {
		if err := movie.ScrapeStatusValidator(v); err != nil {
			return &ValidationError{Name: "scrape_status", err: fmt.Errorf(`ent: validator failed for field "Movie.scrape_status": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(movie.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(movie.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManualCode(); ok {
		_spec.SetField(movie.FieldManualCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CanonicalCode(); ok {
		_spec.SetField(movie.FieldCanonicalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(movie.FieldJavdbID, field.TypeString, value)
	}
	if _u.mutation.JavdbIDCleared() {
		_spec.ClearField(movie.FieldJavdbID, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(movie.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(movie.FieldReleaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(movie.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(movie.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.DirectorID(); ok {
		_spec.SetField(movie.FieldDirectorID, field.TypeString, value)
	}
	if _u.mutation.DirectorIDCleared() {
		_spec.ClearField(movie.FieldDirectorID, field.TypeString)
	}
	if value, ok := _u.mutation.DirectorName(); ok {
		_spec.SetField(movie.FieldDirectorName, field.TypeString, value)
	}
	if _u.mutation.DirectorNameCleared() {
		_spec.ClearField(movie.FieldDirectorName, field.TypeString)
	}
	if value, ok := _u.mutation.MakerID(); ok {
		_spec.SetField(movie.FieldMakerID, field.TypeString, value)
	}
	if _u.mutation.MakerIDCleared() {
		_spec.ClearField(movie.FieldMakerID, field.TypeString)
	}
	if value, ok := _u.mutation.MakerName(); ok {
		_spec.SetField(movie.FieldMakerName, field.TypeString, value)
	}
	if _u.mutation.MakerNameCleared() {
		_spec.ClearField(movie.FieldMakerName, field.TypeString)
	}
	if value, ok := _u.mutation.SeriesID(); ok {
		_spec.SetField(movie.FieldSeriesID, field.TypeString, value)
	}
	if _u.mutation.SeriesIDCleared() {
		_spec.ClearField(movie.FieldSeriesID, field.TypeString)
	}
	if value, ok := _u.mutation.SeriesName(); ok {
		_spec.SetField(movie.FieldSeriesName, field.TypeString, value)
	}
	if _u.mutation.SeriesNameCleared() {
		_spec.ClearField(movie.FieldSeriesName, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(movie.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(movie.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(movie.FieldRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(movie.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(movie.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Poster(); ok {
		_spec.SetField(movie.FieldPoster, field.TypeString, value)
	}
	if _u.mutation.PosterCleared() {
		_spec.ClearField(movie.FieldPoster, field.TypeString)
	}
	if value, ok := _u.mutation.Fanarts(); ok {
		_spec.SetField(movie.FieldFanarts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFanarts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, movie.FieldFanarts, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(movie.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(movie.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.MetadataSnapshot(); ok {
		_spec.SetField(movie.FieldMetadataSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.MetadataSnapshotCleared() {
		_spec.ClearField(movie.FieldMetadataSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScrapeStatus(); ok {
		_spec.SetField(movie.FieldScrapeStatus, field.TypeEnum, value)
	}
	if _u.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActorsIDs(); len(nodes) > 0 && !_u.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubtitlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubtitlesIDs(); len(nodes) > 0 && !_u.mutation.SubtitlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubtitlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MovieUpdateOne is the builder for updating a single Movie entity.
type MovieUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovieMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MovieUpdateOne) SetUpdatedAt(v time.Time) *MovieUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *MovieUpdateOne) SetCode(v string) *MovieUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableCode(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetManualCode sets the "manual_code" field.
func (_u *MovieUpdateOne) SetManualCode(v string) *MovieUpdateOne {
	_u.mutation.SetManualCode(v)
	return _u
}

// SetNillableManualCode sets the "manual_code" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableManualCode(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetManualCode(*v)
	}
	return _u
}

// SetCanonicalCode sets the "canonical_code" field.
func (_u *MovieUpdateOne) SetCanonicalCode(v string) *MovieUpdateOne {
	_u.mutation.SetCanonicalCode(v)
	return _u
}

// SetNillableCanonicalCode sets the "canonical_code" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableCanonicalCode(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetCanonicalCode(*v)
	}
	return _u
}

// SetJavdbID sets the "javdb_id" field.
func (_u *MovieUpdateOne) SetJavdbID(v string) *MovieUpdateOne {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableJavdbID(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// ClearJavdbID clears the value of the "javdb_id" field.
func (_u *MovieUpdateOne) ClearJavdbID() *MovieUpdateOne {
	_u.mutation.ClearJavdbID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *MovieUpdateOne) SetTitle(v string) *MovieUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableTitle(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MovieUpdateOne) SetReleaseDate(v time.Time) *MovieUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableReleaseDate(v *time.Time) *MovieUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *MovieUpdateOne) ClearReleaseDate() *MovieUpdateOne {
	_u.mutation.ClearReleaseDate()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *MovieUpdateOne) SetDuration(v int) *MovieUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDuration(v *int) *MovieUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *MovieUpdateOne) AddDuration(v int) *MovieUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *MovieUpdateOne) ClearDuration() *MovieUpdateOne {
	_u.mutation.ClearDuration()
	return _u
}

// SetDirectorID sets the "director_id" field.
func (_u *MovieUpdateOne) SetDirectorID(v string) *MovieUpdateOne {
	_u.mutation.SetDirectorID(v)
	return _u
}

// SetNillableDirectorID sets the "director_id" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDirectorID(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetDirectorID(*v)
	}
	return _u
}

// ClearDirectorID clears the value of the "director_id" field.
func (_u *MovieUpdateOne) ClearDirectorID() *MovieUpdateOne {
	_u.mutation.ClearDirectorID()
	return _u
}

// SetDirectorName sets the "director_name" field.
func (_u *MovieUpdateOne) SetDirectorName(v string) *MovieUpdateOne {
	_u.mutation.SetDirectorName(v)
	return _u
}

// SetNillableDirectorName sets the "director_name" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableDirectorName(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetDirectorName(*v)
	}
	return _u
}

// ClearDirectorName clears the value of the "director_name" field.
func (_u *MovieUpdateOne) ClearDirectorName() *MovieUpdateOne {
	_u.mutation.ClearDirectorName()
	return _u
}

// SetMakerID sets the "maker_id" field.
func (_u *MovieUpdateOne) SetMakerID(v string) *MovieUpdateOne {
	_u.mutation.SetMakerID(v)
	return _u
}

// SetNillableMakerID sets the "maker_id" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableMakerID(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetMakerID(*v)
	}
	return _u
}

// ClearMakerID clears the value of the "maker_id" field.
func (_u *MovieUpdateOne) ClearMakerID() *MovieUpdateOne {
	_u.mutation.ClearMakerID()
	return _u
}

// SetMakerName sets the "maker_name" field.
func (_u *MovieUpdateOne) SetMakerName(v string) *MovieUpdateOne {
	_u.mutation.SetMakerName(v)
	return _u
}

// SetNillableMakerName sets the "maker_name" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableMakerName(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetMakerName(*v)
	}
	return _u
}

// ClearMakerName clears the value of the "maker_name" field.
func (_u *MovieUpdateOne) ClearMakerName() *MovieUpdateOne {
	_u.mutation.ClearMakerName()
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *MovieUpdateOne) SetSeriesID(v string) *MovieUpdateOne {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableSeriesID(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// ClearSeriesID clears the value of the "series_id" field.
func (_u *MovieUpdateOne) ClearSeriesID() *MovieUpdateOne {
	_u.mutation.ClearSeriesID()
	return _u
}

// SetSeriesName sets the "series_name" field.
func (_u *MovieUpdateOne) SetSeriesName(v string) *MovieUpdateOne {
	_u.mutation.SetSeriesName(v)
	return _u
}

// SetNillableSeriesName sets the "series_name" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableSeriesName(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetSeriesName(*v)
	}
	return _u
}

// ClearSeriesName clears the value of the "series_name" field.
func (_u *MovieUpdateOne) ClearSeriesName() *MovieUpdateOne {
	_u.mutation.ClearSeriesName()
	return _u
}

// SetRating sets the "rating" field.
func (_u *MovieUpdateOne) SetRating(v float64) *MovieUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableRating(v *float64) *MovieUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *MovieUpdateOne) AddRating(v float64) *MovieUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *MovieUpdateOne) ClearRating() *MovieUpdateOne {
	_u.mutation.ClearRating()
	return _u
}

// SetCover sets the "cover" field.
func (_u *MovieUpdateOne) SetCover(v string) *MovieUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableCover(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *MovieUpdateOne) ClearCover() *MovieUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetPoster sets the "poster" field.
func (_u *MovieUpdateOne) SetPoster(v string) *MovieUpdateOne {
	_u.mutation.SetPoster(v)
	return _u
}

// SetNillablePoster sets the "poster" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillablePoster(v *string) *MovieUpdateOne {
	if v != nil {
		_u.SetPoster(*v)
	}
	return _u
}

// ClearPoster clears the value of the "poster" field.
func (_u *MovieUpdateOne) ClearPoster() *MovieUpdateOne {
	_u.mutation.ClearPoster()
	return _u
}

// SetFanarts sets the "fanarts" field.
func (_u *MovieUpdateOne) SetFanarts(v []string) *MovieUpdateOne {
	_u.mutation.SetFanarts(v)
	return _u
}

// AppendFanarts appends value to the "fanarts" field.
func (_u *MovieUpdateOne) AppendFanarts(v []string) *MovieUpdateOne {
	_u.mutation.AppendFanarts(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MovieUpdateOne) SetMetadata(v *nfo.Movie) *MovieUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MovieUpdateOne) ClearMetadata() *MovieUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetMetadataSnapshot sets the "metadata_snapshot" field.
func (_u *MovieUpdateOne) SetMetadataSnapshot(v *domain.MetadataSnapshot) *MovieUpdateOne {
	_u.mutation.SetMetadataSnapshot(v)
	return _u
}

// ClearMetadataSnapshot clears the value of the "metadata_snapshot" field.
func (_u *MovieUpdateOne) ClearMetadataSnapshot() *MovieUpdateOne {
	_u.mutation.ClearMetadataSnapshot()
	return _u
}

// SetScrapeStatus sets the "scrape_status" field.
func (_u *MovieUpdateOne) SetScrapeStatus(v movie.ScrapeStatus) *MovieUpdateOne {
	_u.mutation.SetScrapeStatus(v)
	return _u
}

// SetNillableScrapeStatus sets the "scrape_status" field if the given value is not nil.
func (_u *MovieUpdateOne) SetNillableScrapeStatus(v *movie.ScrapeStatus) *MovieUpdateOne {
	if v != nil {
		_u.SetScrapeStatus(*v)
	}
	return _u
}

// AddActorIDs adds the "actors" edge to the Actor entity by IDs.
func (_u *MovieUpdateOne) AddActorIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.AddActorIDs(ids...)
	return _u
}

// AddActors adds the "actors" edges to the Actor entity.
func (_u *MovieUpdateOne) AddActors(v ...*Actor) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActorIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *MovieUpdateOne) AddTagIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *MovieUpdateOne) AddTags(v ...*Tag) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *MovieUpdateOne) AddFileIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *MovieUpdateOne) AddFiles(v ...*File) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// AddSubtitleIDs adds the "subtitles" edge to the Subtitle entity by IDs.
func (_u *MovieUpdateOne) AddSubtitleIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.AddSubtitleIDs(ids...)
	return _u
}

// AddSubtitles adds the "subtitles" edges to the Subtitle entity.
func (_u *MovieUpdateOne) AddSubtitles(v ...*Subtitle) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubtitleIDs(ids...)
}

// Mutation returns the MovieMutation object of the builder.
func (_u *MovieUpdateOne) Mutation() *MovieMutation {
	return _u.mutation
}

// ClearActors clears all "actors" edges to the Actor entity.
func (_u *MovieUpdateOne) ClearActors() *MovieUpdateOne {
	_u.mutation.ClearActors()
	return _u
}

// RemoveActorIDs removes the "actors" edge to Actor entities by IDs.
func (_u *MovieUpdateOne) RemoveActorIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.RemoveActorIDs(ids...)
	return _u
}

// RemoveActors removes "actors" edges to Actor entities.
func (_u *MovieUpdateOne) RemoveActors(v ...*Actor) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActorIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *MovieUpdateOne) ClearTags() *MovieUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *MovieUpdateOne) RemoveTagIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *MovieUpdateOne) RemoveTags(v ...*Tag) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *MovieUpdateOne) ClearFiles() *MovieUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *MovieUpdateOne) RemoveFileIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *MovieUpdateOne) RemoveFiles(v ...*File) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// ClearSubtitles clears all "subtitles" edges to the Subtitle entity.
func (_u *MovieUpdateOne) ClearSubtitles() *MovieUpdateOne {
	_u.mutation.ClearSubtitles()
	return _u
}

// RemoveSubtitleIDs removes the "subtitles" edge to Subtitle entities by IDs.
func (_u *MovieUpdateOne) RemoveSubtitleIDs(ids ...int) *MovieUpdateOne {
	_u.mutation.RemoveSubtitleIDs(ids...)
	return _u
}

// RemoveSubtitles removes "subtitles" edges to Subtitle entities.
func (_u *MovieUpdateOne) RemoveSubtitles(v ...*Subtitle) *MovieUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubtitleIDs(ids...)
}

// Where appends a list predicates to the MovieUpdate builder.
func (_u *MovieUpdateOne) Where(ps ...predicate.Movie) *MovieUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MovieUpdateOne) Select(field string, fields ...string) *MovieUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Movie entity.
func (_u *MovieUpdateOne) Save(ctx context.Context) (*Movie, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieUpdateOne) SaveX(ctx context.Context) *Movie {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MovieUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MovieUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if movie.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized movie.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := movie.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *MovieUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := movie.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Movie.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScrapeStatus(); ok {
		if err := movie.ScrapeStatusValidator(v); err != nil {
			return &ValidationError{Name: "scrape_status", err: fmt.Errorf(`ent: validator failed for field "Movie.scrape_status": %w`, err)}
		}
	}
	return nil
}

func (_u *MovieUpdateOne) sqlSave(ctx context.Context) (_node *Movie, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(movie.Table, movie.Columns, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Movie.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, movie.FieldID)
		for _, f := range fields {
			if !movie.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != movie.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(movie.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(movie.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManualCode(); ok {
		_spec.SetField(movie.FieldManualCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CanonicalCode(); ok {
		_spec.SetField(movie.FieldCanonicalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(movie.FieldJavdbID, field.TypeString, value)
	}
	if _u.mutation.JavdbIDCleared() {
		_spec.ClearField(movie.FieldJavdbID, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(movie.FieldReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(movie.FieldReleaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(movie.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(movie.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(movie.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.DirectorID(); ok {
		_spec.SetField(movie.FieldDirectorID, field.TypeString, value)
	}
	if _u.mutation.DirectorIDCleared() {
		_spec.ClearField(movie.FieldDirectorID, field.TypeString)
	}
	if value, ok := _u.mutation.DirectorName(); ok {
		_spec.SetField(movie.FieldDirectorName, field.TypeString, value)
	}
	if _u.mutation.DirectorNameCleared() {
		_spec.ClearField(movie.FieldDirectorName, field.TypeString)
	}
	if value, ok := _u.mutation.MakerID(); ok {
		_spec.SetField(movie.FieldMakerID, field.TypeString, value)
	}
	if _u.mutation.MakerIDCleared() {
		_spec.ClearField(movie.FieldMakerID, field.TypeString)
	}
	if value, ok := _u.mutation.MakerName(); ok {
		_spec.SetField(movie.FieldMakerName, field.TypeString, value)
	}
	if _u.mutation.MakerNameCleared() {
		_spec.ClearField(movie.FieldMakerName, field.TypeString)
	}
	if value, ok := _u.mutation.SeriesID(); ok {
		_spec.SetField(movie.FieldSeriesID, field.TypeString, value)
	}
	if _u.mutation.SeriesIDCleared() {
		_spec.ClearField(movie.FieldSeriesID, field.TypeString)
	}
	if value, ok := _u.mutation.SeriesName(); ok {
		_spec.SetField(movie.FieldSeriesName, field.TypeString, value)
	}
	if _u.mutation.SeriesNameCleared() {
		_spec.ClearField(movie.FieldSeriesName, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(movie.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(movie.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(movie.FieldRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(movie.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(movie.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Poster(); ok {
		_spec.SetField(movie.FieldPoster, field.TypeString, value)
	}
	if _u.mutation.PosterCleared() {
		_spec.ClearField(movie.FieldPoster, field.TypeString)
	}
	if value, ok := _u.mutation.Fanarts(); ok {
		_spec.SetField(movie.FieldFanarts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFanarts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, movie.FieldFanarts, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(movie.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(movie.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.MetadataSnapshot(); ok {
		_spec.SetField(movie.FieldMetadataSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.MetadataSnapshotCleared() {
		_spec.ClearField(movie.FieldMetadataSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScrapeStatus(); ok {
		_spec.SetField(movie.FieldScrapeStatus, field.TypeEnum, value)
	}
	if _u.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActorsIDs(); len(nodes) > 0 && !_u.mutation.ActorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.ActorsTable,
			Columns: movie.ActorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   movie.TagsTable,
			Columns: movie.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.FilesTable,
			Columns: []string{movie.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubtitlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubtitlesIDs(); len(nodes) > 0 && !_u.mutation.SubtitlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubtitlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   movie.SubtitlesTable,
			Columns: []string{movie.SubtitlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtitle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Movie{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{movie.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
