// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/domain"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/nfo"
)

// Movie is the model entity for the Movie schema.
type Movie struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// ManualCode holds the value of the "manual_code" field.
	ManualCode string `json:"manual_code,omitempty"`
	// Candidate grouping key; equivalence must still be checked against code.
	CanonicalCode string `json:"canonical_code,omitempty"`
	// JavdbID holds the value of the "javdb_id" field.
	JavdbID *string `json:"javdb_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// ReleaseDate holds the value of the "release_date" field.
	ReleaseDate *time.Time `json:"release_date,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration *int `json:"duration,omitempty"`
	// DirectorID holds the value of the "director_id" field.
	DirectorID *string `json:"director_id,omitempty"`
	// DirectorName holds the value of the "director_name" field.
	DirectorName *string `json:"director_name,omitempty"`
	// MakerID holds the value of the "maker_id" field.
	MakerID *string `json:"maker_id,omitempty"`
	// MakerName holds the value of the "maker_name" field.
	MakerName *string `json:"maker_name,omitempty"`
	// SeriesID holds the value of the "series_id" field.
	SeriesID *string `json:"series_id,omitempty"`
	// SeriesName holds the value of the "series_name" field.
	SeriesName *string `json:"series_name,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating *float64 `json:"rating,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover *string `json:"cover,omitempty"`
	// Poster holds the value of the "poster" field.
	Poster *string `json:"poster,omitempty"`
	// Fanarts holds the value of the "fanarts" field.
	Fanarts []string `json:"fanarts,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata *nfo.Movie `json:"metadata,omitempty"`
	// MetadataSnapshot holds the value of the "metadata_snapshot" field.
	MetadataSnapshot *domain.MetadataSnapshot `json:"metadata_snapshot,omitempty"`
	// ScrapeStatus holds the value of the "scrape_status" field.
	ScrapeStatus movie.ScrapeStatus `json:"scrape_status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MovieQuery when eager-loading is set.
	Edges        MovieEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MovieEdges holds the relations/edges for other nodes in the graph.
type MovieEdges struct {
	// Actors holds the value of the actors edge.
	Actors []*Actor `json:"actors,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Files holds the value of the files edge.
	Files []*File `json:"files,omitempty"`
	// Subtitles holds the value of the subtitles edge.
	Subtitles []*Subtitle `json:"subtitles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ActorsOrErr returns the Actors value or an error if the edge
// was not loaded in eager-loading.
func (e MovieEdges) ActorsOrErr() ([]*Actor, error) {
	if e.loadedTypes[0] {
		return e.Actors, nil
	}
	return nil, &NotLoadedError{edge: "actors"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e MovieEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e MovieEdges) FilesOrErr() ([]*File, error) {
	if e.loadedTypes[2] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// SubtitlesOrErr returns the Subtitles value or an error if the edge
// was not loaded in eager-loading.
func (e MovieEdges) SubtitlesOrErr() ([]*Subtitle, error) {
	if e.loadedTypes[3] {
		return e.Subtitles, nil
	}
	return nil, &NotLoadedError{edge: "subtitles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Movie) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case movie.FieldFanarts, movie.FieldMetadata, movie.FieldMetadataSnapshot:
			values[i] = new([]byte)
		case movie.FieldRating:
			values[i] = new(sql.NullFloat64)
		case movie.FieldID, movie.FieldDuration:
			values[i] = new(sql.NullInt64)
		case movie.FieldCode, movie.FieldManualCode, movie.FieldCanonicalCode, movie.FieldJavdbID, movie.FieldTitle, movie.FieldDirectorID, movie.FieldDirectorName, movie.FieldMakerID, movie.FieldMakerName, movie.FieldSeriesID, movie.FieldSeriesName, movie.FieldCover, movie.FieldPoster, movie.FieldScrapeStatus:
			values[i] = new(sql.NullString)
		case movie.FieldCreatedAt, movie.FieldUpdatedAt, movie.FieldReleaseDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Movie fields.
func (_m *Movie) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case movie.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case movie.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case movie.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case movie.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case movie.FieldManualCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_code", values[i])
			} else if value.Valid {
				_m.ManualCode = value.String
			}
		case movie.FieldCanonicalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_code", values[i])
			} else if value.Valid {
				_m.CanonicalCode = value.String
			}
		case movie.FieldJavdbID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field javdb_id", values[i])
			} else if value.Valid {
				_m.JavdbID = new(string)
				*_m.JavdbID = value.String
			}
		case movie.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case movie.FieldReleaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field release_date", values[i])
			} else if value.Valid {
				_m.ReleaseDate = new(time.Time)
				*_m.ReleaseDate = value.Time
			}
		case movie.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				_m.Duration = new(int)
				*_m.Duration = int(value.Int64)
			}
		case movie.FieldDirectorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field director_id", values[i])
			} else if value.Valid {
				_m.DirectorID = new(string)
				*_m.DirectorID = value.String
			}
		case movie.FieldDirectorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field director_name", values[i])
			} else if value.Valid {
				_m.DirectorName = new(string)
				*_m.DirectorName = value.String
			}
		case movie.FieldMakerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field maker_id", values[i])
			} else if value.Valid {
				_m.MakerID = new(string)
				*_m.MakerID = value.String
			}
		case movie.FieldMakerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field maker_name", values[i])
			} else if value.Valid {
				_m.MakerName = new(string)
				*_m.MakerName = value.String
			}
		case movie.FieldSeriesID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field series_id", values[i])
			} else if value.Valid {
				_m.SeriesID = new(string)
				*_m.SeriesID = value.String
			}
		case movie.FieldSeriesName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field series_name", values[i])
			} else if value.Valid {
				_m.SeriesName = new(string)
				*_m.SeriesName = value.String
			}
		case movie.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = new(float64)
				*_m.Rating = value.Float64
			}
		case movie.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				_m.Cover = new(string)
				*_m.Cover = value.String
			}
		case movie.FieldPoster:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field poster", values[i])
			} else if value.Valid {
				_m.Poster = new(string)
				*_m.Poster = value.String
			}
		case movie.FieldFanarts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field fanarts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Fanarts); err != nil {
					return fmt.Errorf("unmarshal field fanarts: %w", err)
				}
			}
		case movie.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case movie.FieldMetadataSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MetadataSnapshot); err != nil {
					return fmt.Errorf("unmarshal field metadata_snapshot: %w", err)
				}
			}
		case movie.FieldScrapeStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scrape_status", values[i])
			} else if value.Valid {
				_m.ScrapeStatus = movie.ScrapeStatus(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Movie.
// This includes values selected through modifiers, order, etc.
func (_m *Movie) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActors queries the "actors" edge of the Movie entity.
func (_m *Movie) QueryActors() *ActorQuery {
	return NewMovieClient(_m.config).QueryActors(_m)
}

// QueryTags queries the "tags" edge of the Movie entity.
func (_m *Movie) QueryTags() *TagQuery {
	return NewMovieClient(_m.config).QueryTags(_m)
}

// QueryFiles queries the "files" edge of the Movie entity.
func (_m *Movie) QueryFiles() *FileQuery {
	return NewMovieClient(_m.config).QueryFiles(_m)
}

// QuerySubtitles queries the "subtitles" edge of the Movie entity.
func (_m *Movie) QuerySubtitles() *SubtitleQuery {
	return NewMovieClient(_m.config).QuerySubtitles(_m)
}

// Update returns a builder for updating this Movie.
// Note that you need to call Movie.Unwrap() before calling this method if this Movie
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Movie) Update() *MovieUpdateOne {
	return NewMovieClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Movie entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Movie) Unwrap() *Movie {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Movie is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Movie) String() string {
	var builder strings.Builder
	builder.WriteString("Movie(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("manual_code=")
	builder.WriteString(_m.ManualCode)
	builder.WriteString(", ")
	builder.WriteString("canonical_code=")
	builder.WriteString(_m.CanonicalCode)
	builder.WriteString(", ")
	if v := _m.JavdbID; v != nil {
		builder.WriteString("javdb_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.ReleaseDate; v != nil {
		builder.WriteString("release_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Duration; v != nil {
		builder.WriteString("duration=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DirectorID; v != nil {
		builder.WriteString("director_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DirectorName; v != nil {
		builder.WriteString("director_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MakerID; v != nil {
		builder.WriteString("maker_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MakerName; v != nil {
		builder.WriteString("maker_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SeriesID; v != nil {
		builder.WriteString("series_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SeriesName; v != nil {
		builder.WriteString("series_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Rating; v != nil {
		builder.WriteString("rating=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Cover; v != nil {
		builder.WriteString("cover=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Poster; v != nil {
		builder.WriteString("poster=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("fanarts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Fanarts))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("metadata_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataSnapshot))
	builder.WriteString(", ")
	builder.WriteString("scrape_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScrapeStatus))
	builder.WriteByte(')')
	return builder.String()
}

// Movies is a parsable slice of Movie.
type Movies []*Movie
