// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/domain/download"
	"github.com/ppxb/miyabi/internal/ent/offlinedownload"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// OfflineDownloadUpdate is the builder for updating OfflineDownload entities.
type OfflineDownloadUpdate struct {
	config
	hooks    []Hook
	mutation *OfflineDownloadMutation
}

// Where appends a list predicates to the OfflineDownloadUpdate builder.
func (_u *OfflineDownloadUpdate) Where(ps ...predicate.OfflineDownload) *OfflineDownloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OfflineDownloadUpdate) SetUpdatedAt(v time.Time) *OfflineDownloadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *OfflineDownloadUpdate) SetCode(v string) *OfflineDownloadUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableCode(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetJavdbID sets the "javdb_id" field.
func (_u *OfflineDownloadUpdate) SetJavdbID(v string) *OfflineDownloadUpdate {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableJavdbID(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *OfflineDownloadUpdate) SetHash(v string) *OfflineDownloadUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableHash(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetInfoHash sets the "info_hash" field.
func (_u *OfflineDownloadUpdate) SetInfoHash(v string) *OfflineDownloadUpdate {
	_u.mutation.SetInfoHash(v)
	return _u
}

// SetNillableInfoHash sets the "info_hash" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableInfoHash(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetInfoHash(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OfflineDownloadUpdate) SetAccountID(v string) *OfflineDownloadUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableAccountID(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetDirectoryID sets the "directory_id" field.
func (_u *OfflineDownloadUpdate) SetDirectoryID(v string) *OfflineDownloadUpdate {
	_u.mutation.SetDirectoryID(v)
	return _u
}

// SetNillableDirectoryID sets the "directory_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableDirectoryID(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetDirectoryID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OfflineDownloadUpdate) SetStatus(v offlinedownload.Status) *OfflineDownloadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableStatus(v *offlinedownload.Status) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecovery sets the "recovery" field.
func (_u *OfflineDownloadUpdate) SetRecovery(v *download.Recovery) *OfflineDownloadUpdate {
	_u.mutation.SetRecovery(v)
	return _u
}

// ClearRecovery clears the value of the "recovery" field.
func (_u *OfflineDownloadUpdate) ClearRecovery() *OfflineDownloadUpdate {
	_u.mutation.ClearRecovery()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *OfflineDownloadUpdate) SetProgress(v int) *OfflineDownloadUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableProgress(v *int) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *OfflineDownloadUpdate) AddProgress(v int) *OfflineDownloadUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetError sets the "error" field.
func (_u *OfflineDownloadUpdate) SetError(v string) *OfflineDownloadUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableError(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *OfflineDownloadUpdate) ClearError() *OfflineDownloadUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *OfflineDownloadUpdate) SetFileID(v string) *OfflineDownloadUpdate {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableFileID(v *string) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetFileIds sets the "file_ids" field.
func (_u *OfflineDownloadUpdate) SetFileIds(v []string) *OfflineDownloadUpdate {
	_u.mutation.SetFileIds(v)
	return _u
}

// AppendFileIds appends value to the "file_ids" field.
func (_u *OfflineDownloadUpdate) AppendFileIds(v []string) *OfflineDownloadUpdate {
	_u.mutation.AppendFileIds(v)
	return _u
}

// SetScanTaskID sets the "scan_task_id" field.
func (_u *OfflineDownloadUpdate) SetScanTaskID(v int) *OfflineDownloadUpdate {
	_u.mutation.ResetScanTaskID()
	_u.mutation.SetScanTaskID(v)
	return _u
}

// SetNillableScanTaskID sets the "scan_task_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableScanTaskID(v *int) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetScanTaskID(*v)
	}
	return _u
}

// AddScanTaskID adds value to the "scan_task_id" field.
func (_u *OfflineDownloadUpdate) AddScanTaskID(v int) *OfflineDownloadUpdate {
	_u.mutation.AddScanTaskID(v)
	return _u
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (_u *OfflineDownloadUpdate) SetAwaitingLocation(v bool) *OfflineDownloadUpdate {
	_u.mutation.SetAwaitingLocation(v)
	return _u
}

// SetNillableAwaitingLocation sets the "awaiting_location" field if the given value is not nil.
func (_u *OfflineDownloadUpdate) SetNillableAwaitingLocation(v *bool) *OfflineDownloadUpdate {
	if v != nil {
		_u.SetAwaitingLocation(*v)
	}
	return _u
}

// Mutation returns the OfflineDownloadMutation object of the builder.
func (_u *OfflineDownloadUpdate) Mutation() *OfflineDownloadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OfflineDownloadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OfflineDownloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OfflineDownloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OfflineDownloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OfflineDownloadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := offlinedownload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OfflineDownloadUpdate) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := offlinedownload.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := offlinedownload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := offlinedownload.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.progress": %w`, err)}
		}
	}
	return nil
}

func (_u *OfflineDownloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(offlinedownload.Table, offlinedownload.Columns, sqlgraph.NewFieldSpec(offlinedownload.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(offlinedownload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(offlinedownload.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(offlinedownload.FieldJavdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(offlinedownload.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InfoHash(); ok {
		_spec.SetField(offlinedownload.FieldInfoHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(offlinedownload.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DirectoryID(); ok {
		_spec.SetField(offlinedownload.FieldDirectoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(offlinedownload.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Recovery(); ok {
		_spec.SetField(offlinedownload.FieldRecovery, field.TypeJSON, value)
	}
	if _u.mutation.RecoveryCleared() {
		_spec.ClearField(offlinedownload.FieldRecovery, field.TypeJSON)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(offlinedownload.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(offlinedownload.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(offlinedownload.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(offlinedownload.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(offlinedownload.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileIds(); ok {
		_spec.SetField(offlinedownload.FieldFileIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, offlinedownload.FieldFileIds, value)
		})
	}
	if value, ok := _u.mutation.ScanTaskID(); ok {
		_spec.SetField(offlinedownload.FieldScanTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScanTaskID(); ok {
		_spec.AddField(offlinedownload.FieldScanTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AwaitingLocation(); ok {
		_spec.SetField(offlinedownload.FieldAwaitingLocation, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{offlinedownload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OfflineDownloadUpdateOne is the builder for updating a single OfflineDownload entity.
type OfflineDownloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OfflineDownloadMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OfflineDownloadUpdateOne) SetUpdatedAt(v time.Time) *OfflineDownloadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *OfflineDownloadUpdateOne) SetCode(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableCode(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetJavdbID sets the "javdb_id" field.
func (_u *OfflineDownloadUpdateOne) SetJavdbID(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetJavdbID(v)
	return _u
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableJavdbID(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetJavdbID(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *OfflineDownloadUpdateOne) SetHash(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableHash(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetInfoHash sets the "info_hash" field.
func (_u *OfflineDownloadUpdateOne) SetInfoHash(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetInfoHash(v)
	return _u
}

// SetNillableInfoHash sets the "info_hash" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableInfoHash(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetInfoHash(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OfflineDownloadUpdateOne) SetAccountID(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableAccountID(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetDirectoryID sets the "directory_id" field.
func (_u *OfflineDownloadUpdateOne) SetDirectoryID(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetDirectoryID(v)
	return _u
}

// SetNillableDirectoryID sets the "directory_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableDirectoryID(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetDirectoryID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OfflineDownloadUpdateOne) SetStatus(v offlinedownload.Status) *OfflineDownloadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableStatus(v *offlinedownload.Status) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRecovery sets the "recovery" field.
func (_u *OfflineDownloadUpdateOne) SetRecovery(v *download.Recovery) *OfflineDownloadUpdateOne {
	_u.mutation.SetRecovery(v)
	return _u
}

// ClearRecovery clears the value of the "recovery" field.
func (_u *OfflineDownloadUpdateOne) ClearRecovery() *OfflineDownloadUpdateOne {
	_u.mutation.ClearRecovery()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *OfflineDownloadUpdateOne) SetProgress(v int) *OfflineDownloadUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableProgress(v *int) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *OfflineDownloadUpdateOne) AddProgress(v int) *OfflineDownloadUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetError sets the "error" field.
func (_u *OfflineDownloadUpdateOne) SetError(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableError(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *OfflineDownloadUpdateOne) ClearError() *OfflineDownloadUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetFileID sets the "file_id" field.
func (_u *OfflineDownloadUpdateOne) SetFileID(v string) *OfflineDownloadUpdateOne {
	_u.mutation.SetFileID(v)
	return _u
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableFileID(v *string) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetFileID(*v)
	}
	return _u
}

// SetFileIds sets the "file_ids" field.
func (_u *OfflineDownloadUpdateOne) SetFileIds(v []string) *OfflineDownloadUpdateOne {
	_u.mutation.SetFileIds(v)
	return _u
}

// AppendFileIds appends value to the "file_ids" field.
func (_u *OfflineDownloadUpdateOne) AppendFileIds(v []string) *OfflineDownloadUpdateOne {
	_u.mutation.AppendFileIds(v)
	return _u
}

// SetScanTaskID sets the "scan_task_id" field.
func (_u *OfflineDownloadUpdateOne) SetScanTaskID(v int) *OfflineDownloadUpdateOne {
	_u.mutation.ResetScanTaskID()
	_u.mutation.SetScanTaskID(v)
	return _u
}

// SetNillableScanTaskID sets the "scan_task_id" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableScanTaskID(v *int) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetScanTaskID(*v)
	}
	return _u
}

// AddScanTaskID adds value to the "scan_task_id" field.
func (_u *OfflineDownloadUpdateOne) AddScanTaskID(v int) *OfflineDownloadUpdateOne {
	_u.mutation.AddScanTaskID(v)
	return _u
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (_u *OfflineDownloadUpdateOne) SetAwaitingLocation(v bool) *OfflineDownloadUpdateOne {
	_u.mutation.SetAwaitingLocation(v)
	return _u
}

// SetNillableAwaitingLocation sets the "awaiting_location" field if the given value is not nil.
func (_u *OfflineDownloadUpdateOne) SetNillableAwaitingLocation(v *bool) *OfflineDownloadUpdateOne {
	if v != nil {
		_u.SetAwaitingLocation(*v)
	}
	return _u
}

// Mutation returns the OfflineDownloadMutation object of the builder.
func (_u *OfflineDownloadUpdateOne) Mutation() *OfflineDownloadMutation {
	return _u.mutation
}

// Where appends a list predicates to the OfflineDownloadUpdate builder.
func (_u *OfflineDownloadUpdateOne) Where(ps ...predicate.OfflineDownload) *OfflineDownloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OfflineDownloadUpdateOne) Select(field string, fields ...string) *OfflineDownloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OfflineDownload entity.
func (_u *OfflineDownloadUpdateOne) Save(ctx context.Context) (*OfflineDownload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OfflineDownloadUpdateOne) SaveX(ctx context.Context) *OfflineDownload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OfflineDownloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OfflineDownloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OfflineDownloadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := offlinedownload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OfflineDownloadUpdateOne) check() error {
	if v, ok := _u.mutation.Hash(); ok {
		if err := offlinedownload.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := offlinedownload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := offlinedownload.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.progress": %w`, err)}
		}
	}
	return nil
}

func (_u *OfflineDownloadUpdateOne) sqlSave(ctx context.Context) (_node *OfflineDownload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(offlinedownload.Table, offlinedownload.Columns, sqlgraph.NewFieldSpec(offlinedownload.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OfflineDownload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, offlinedownload.FieldID)
		for _, f := range fields {
			if !offlinedownload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != offlinedownload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(offlinedownload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(offlinedownload.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JavdbID(); ok {
		_spec.SetField(offlinedownload.FieldJavdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(offlinedownload.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InfoHash(); ok {
		_spec.SetField(offlinedownload.FieldInfoHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(offlinedownload.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DirectoryID(); ok {
		_spec.SetField(offlinedownload.FieldDirectoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(offlinedownload.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Recovery(); ok {
		_spec.SetField(offlinedownload.FieldRecovery, field.TypeJSON, value)
	}
	if _u.mutation.RecoveryCleared() {
		_spec.ClearField(offlinedownload.FieldRecovery, field.TypeJSON)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(offlinedownload.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(offlinedownload.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(offlinedownload.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(offlinedownload.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.FileID(); ok {
		_spec.SetField(offlinedownload.FieldFileID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileIds(); ok {
		_spec.SetField(offlinedownload.FieldFileIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, offlinedownload.FieldFileIds, value)
		})
	}
	if value, ok := _u.mutation.ScanTaskID(); ok {
		_spec.SetField(offlinedownload.FieldScanTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScanTaskID(); ok {
		_spec.AddField(offlinedownload.FieldScanTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AwaitingLocation(); ok {
		_spec.SetField(offlinedownload.FieldAwaitingLocation, field.TypeBool, value)
	}
	_node = &OfflineDownload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{offlinedownload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
