// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/domain/download"
	"github.com/ppxb/miyabi/internal/ent/offlinedownload"
)

// OfflineDownloadCreate is the builder for creating a OfflineDownload entity.
type OfflineDownloadCreate struct {
	config
	mutation *OfflineDownloadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OfflineDownloadCreate) SetCreatedAt(v time.Time) *OfflineDownloadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableCreatedAt(v *time.Time) *OfflineDownloadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OfflineDownloadCreate) SetUpdatedAt(v time.Time) *OfflineDownloadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableUpdatedAt(v *time.Time) *OfflineDownloadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *OfflineDownloadCreate) SetCode(v string) *OfflineDownloadCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableCode(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetJavdbID sets the "javdb_id" field.
func (_c *OfflineDownloadCreate) SetJavdbID(v string) *OfflineDownloadCreate {
	_c.mutation.SetJavdbID(v)
	return _c
}

// SetNillableJavdbID sets the "javdb_id" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableJavdbID(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetJavdbID(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *OfflineDownloadCreate) SetHash(v string) *OfflineDownloadCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetInfoHash sets the "info_hash" field.
func (_c *OfflineDownloadCreate) SetInfoHash(v string) *OfflineDownloadCreate {
	_c.mutation.SetInfoHash(v)
	return _c
}

// SetNillableInfoHash sets the "info_hash" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableInfoHash(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetInfoHash(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OfflineDownloadCreate) SetAccountID(v string) *OfflineDownloadCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableAccountID(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetDirectoryID sets the "directory_id" field.
func (_c *OfflineDownloadCreate) SetDirectoryID(v string) *OfflineDownloadCreate {
	_c.mutation.SetDirectoryID(v)
	return _c
}

// SetNillableDirectoryID sets the "directory_id" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableDirectoryID(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetDirectoryID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OfflineDownloadCreate) SetStatus(v offlinedownload.Status) *OfflineDownloadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableStatus(v *offlinedownload.Status) *OfflineDownloadCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRecovery sets the "recovery" field.
func (_c *OfflineDownloadCreate) SetRecovery(v *download.Recovery) *OfflineDownloadCreate {
	_c.mutation.SetRecovery(v)
	return _c
}

// SetProgress sets the "progress" field.
func (_c *OfflineDownloadCreate) SetProgress(v int) *OfflineDownloadCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableProgress(v *int) *OfflineDownloadCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *OfflineDownloadCreate) SetError(v string) *OfflineDownloadCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableError(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *OfflineDownloadCreate) SetFileID(v string) *OfflineDownloadCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableFileID(v *string) *OfflineDownloadCreate {
	if v != nil {
		_c.SetFileID(*v)
	}
	return _c
}

// SetFileIds sets the "file_ids" field.
func (_c *OfflineDownloadCreate) SetFileIds(v []string) *OfflineDownloadCreate {
	_c.mutation.SetFileIds(v)
	return _c
}

// SetScanTaskID sets the "scan_task_id" field.
func (_c *OfflineDownloadCreate) SetScanTaskID(v int) *OfflineDownloadCreate {
	_c.mutation.SetScanTaskID(v)
	return _c
}

// SetNillableScanTaskID sets the "scan_task_id" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableScanTaskID(v *int) *OfflineDownloadCreate {
	if v != nil {
		_c.SetScanTaskID(*v)
	}
	return _c
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (_c *OfflineDownloadCreate) SetAwaitingLocation(v bool) *OfflineDownloadCreate {
	_c.mutation.SetAwaitingLocation(v)
	return _c
}

// SetNillableAwaitingLocation sets the "awaiting_location" field if the given value is not nil.
func (_c *OfflineDownloadCreate) SetNillableAwaitingLocation(v *bool) *OfflineDownloadCreate {
	if v != nil {
		_c.SetAwaitingLocation(*v)
	}
	return _c
}

// Mutation returns the OfflineDownloadMutation object of the builder.
func (_c *OfflineDownloadCreate) Mutation() *OfflineDownloadMutation {
	return _c.mutation
}

// Save creates the OfflineDownload in the database.
func (_c *OfflineDownloadCreate) Save(ctx context.Context) (*OfflineDownload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OfflineDownloadCreate) SaveX(ctx context.Context) *OfflineDownload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineDownloadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineDownloadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OfflineDownloadCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := offlinedownload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := offlinedownload.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Code(); !ok {
		v := offlinedownload.DefaultCode
		_c.mutation.SetCode(v)
	}
	if _, ok := _c.mutation.JavdbID(); !ok {
		v := offlinedownload.DefaultJavdbID
		_c.mutation.SetJavdbID(v)
	}
	if _, ok := _c.mutation.InfoHash(); !ok {
		v := offlinedownload.DefaultInfoHash
		_c.mutation.SetInfoHash(v)
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		v := offlinedownload.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.DirectoryID(); !ok {
		v := offlinedownload.DefaultDirectoryID
		_c.mutation.SetDirectoryID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := offlinedownload.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := offlinedownload.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.FileID(); !ok {
		v := offlinedownload.DefaultFileID
		_c.mutation.SetFileID(v)
	}
	if _, ok := _c.mutation.FileIds(); !ok {
		v := offlinedownload.DefaultFileIds
		_c.mutation.SetFileIds(v)
	}
	if _, ok := _c.mutation.ScanTaskID(); !ok {
		v := offlinedownload.DefaultScanTaskID
		_c.mutation.SetScanTaskID(v)
	}
	if _, ok := _c.mutation.AwaitingLocation(); !ok {
		v := offlinedownload.DefaultAwaitingLocation
		_c.mutation.SetAwaitingLocation(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OfflineDownloadCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OfflineDownload.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OfflineDownload.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "OfflineDownload.code"`)}
	}
	if _, ok := _c.mutation.JavdbID(); !ok {
		return &ValidationError{Name: "javdb_id", err: errors.New(`ent: missing required field "OfflineDownload.javdb_id"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "OfflineDownload.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := offlinedownload.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InfoHash(); !ok {
		return &ValidationError{Name: "info_hash", err: errors.New(`ent: missing required field "OfflineDownload.info_hash"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OfflineDownload.account_id"`)}
	}
	if _, ok := _c.mutation.DirectoryID(); !ok {
		return &ValidationError{Name: "directory_id", err: errors.New(`ent: missing required field "OfflineDownload.directory_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OfflineDownload.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := offlinedownload.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "OfflineDownload.progress"`)}
	}
	if v, ok := _c.mutation.Progress(); ok {
		if err := offlinedownload.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "OfflineDownload.progress": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "OfflineDownload.file_id"`)}
	}
	if _, ok := _c.mutation.FileIds(); !ok {
		return &ValidationError{Name: "file_ids", err: errors.New(`ent: missing required field "OfflineDownload.file_ids"`)}
	}
	if _, ok := _c.mutation.ScanTaskID(); !ok {
		return &ValidationError{Name: "scan_task_id", err: errors.New(`ent: missing required field "OfflineDownload.scan_task_id"`)}
	}
	if _, ok := _c.mutation.AwaitingLocation(); !ok {
		return &ValidationError{Name: "awaiting_location", err: errors.New(`ent: missing required field "OfflineDownload.awaiting_location"`)}
	}
	return nil
}

func (_c *OfflineDownloadCreate) sqlSave(ctx context.Context) (*OfflineDownload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OfflineDownloadCreate) createSpec() (*OfflineDownload, *sqlgraph.CreateSpec) {
	var (
		_node = &OfflineDownload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(offlinedownload.Table, sqlgraph.NewFieldSpec(offlinedownload.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(offlinedownload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(offlinedownload.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(offlinedownload.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.JavdbID(); ok {
		_spec.SetField(offlinedownload.FieldJavdbID, field.TypeString, value)
		_node.JavdbID = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(offlinedownload.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.InfoHash(); ok {
		_spec.SetField(offlinedownload.FieldInfoHash, field.TypeString, value)
		_node.InfoHash = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(offlinedownload.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.DirectoryID(); ok {
		_spec.SetField(offlinedownload.FieldDirectoryID, field.TypeString, value)
		_node.DirectoryID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(offlinedownload.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Recovery(); ok {
		_spec.SetField(offlinedownload.FieldRecovery, field.TypeJSON, value)
		_node.Recovery = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(offlinedownload.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(offlinedownload.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.FileID(); ok {
		_spec.SetField(offlinedownload.FieldFileID, field.TypeString, value)
		_node.FileID = value
	}
	if value, ok := _c.mutation.FileIds(); ok {
		_spec.SetField(offlinedownload.FieldFileIds, field.TypeJSON, value)
		_node.FileIds = value
	}
	if value, ok := _c.mutation.ScanTaskID(); ok {
		_spec.SetField(offlinedownload.FieldScanTaskID, field.TypeInt, value)
		_node.ScanTaskID = value
	}
	if value, ok := _c.mutation.AwaitingLocation(); ok {
		_spec.SetField(offlinedownload.FieldAwaitingLocation, field.TypeBool, value)
		_node.AwaitingLocation = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OfflineDownload.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OfflineDownloadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OfflineDownloadCreate) OnConflict(opts ...sql.ConflictOption) *OfflineDownloadUpsertOne {
	_c.conflict = opts
	return &OfflineDownloadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OfflineDownloadCreate) OnConflictColumns(columns ...string) *OfflineDownloadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OfflineDownloadUpsertOne{
		create: _c,
	}
}

type (
	// OfflineDownloadUpsertOne is the builder for "upsert"-ing
	//  one OfflineDownload node.
	OfflineDownloadUpsertOne struct {
		create *OfflineDownloadCreate
	}

	// OfflineDownloadUpsert is the "OnConflict" setter.
	OfflineDownloadUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OfflineDownloadUpsert) SetUpdatedAt(v time.Time) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateUpdatedAt() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *OfflineDownloadUpsert) SetCode(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateCode() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldCode)
	return u
}

// SetJavdbID sets the "javdb_id" field.
func (u *OfflineDownloadUpsert) SetJavdbID(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldJavdbID, v)
	return u
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateJavdbID() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldJavdbID)
	return u
}

// SetHash sets the "hash" field.
func (u *OfflineDownloadUpsert) SetHash(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateHash() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldHash)
	return u
}

// SetInfoHash sets the "info_hash" field.
func (u *OfflineDownloadUpsert) SetInfoHash(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldInfoHash, v)
	return u
}

// UpdateInfoHash sets the "info_hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateInfoHash() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldInfoHash)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OfflineDownloadUpsert) SetAccountID(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateAccountID() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldAccountID)
	return u
}

// SetDirectoryID sets the "directory_id" field.
func (u *OfflineDownloadUpsert) SetDirectoryID(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldDirectoryID, v)
	return u
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateDirectoryID() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldDirectoryID)
	return u
}

// SetStatus sets the "status" field.
func (u *OfflineDownloadUpsert) SetStatus(v offlinedownload.Status) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateStatus() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldStatus)
	return u
}

// SetRecovery sets the "recovery" field.
func (u *OfflineDownloadUpsert) SetRecovery(v *download.Recovery) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldRecovery, v)
	return u
}

// UpdateRecovery sets the "recovery" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateRecovery() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldRecovery)
	return u
}

// ClearRecovery clears the value of the "recovery" field.
func (u *OfflineDownloadUpsert) ClearRecovery() *OfflineDownloadUpsert {
	u.SetNull(offlinedownload.FieldRecovery)
	return u
}

// SetProgress sets the "progress" field.
func (u *OfflineDownloadUpsert) SetProgress(v int) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldProgress, v)
	return u
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateProgress() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldProgress)
	return u
}

// AddProgress adds v to the "progress" field.
func (u *OfflineDownloadUpsert) AddProgress(v int) *OfflineDownloadUpsert {
	u.Add(offlinedownload.FieldProgress, v)
	return u
}

// SetError sets the "error" field.
func (u *OfflineDownloadUpsert) SetError(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateError() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *OfflineDownloadUpsert) ClearError() *OfflineDownloadUpsert {
	u.SetNull(offlinedownload.FieldError)
	return u
}

// SetFileID sets the "file_id" field.
func (u *OfflineDownloadUpsert) SetFileID(v string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateFileID() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldFileID)
	return u
}

// SetFileIds sets the "file_ids" field.
func (u *OfflineDownloadUpsert) SetFileIds(v []string) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldFileIds, v)
	return u
}

// UpdateFileIds sets the "file_ids" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateFileIds() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldFileIds)
	return u
}

// SetScanTaskID sets the "scan_task_id" field.
func (u *OfflineDownloadUpsert) SetScanTaskID(v int) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldScanTaskID, v)
	return u
}

// UpdateScanTaskID sets the "scan_task_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateScanTaskID() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldScanTaskID)
	return u
}

// AddScanTaskID adds v to the "scan_task_id" field.
func (u *OfflineDownloadUpsert) AddScanTaskID(v int) *OfflineDownloadUpsert {
	u.Add(offlinedownload.FieldScanTaskID, v)
	return u
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (u *OfflineDownloadUpsert) SetAwaitingLocation(v bool) *OfflineDownloadUpsert {
	u.Set(offlinedownload.FieldAwaitingLocation, v)
	return u
}

// UpdateAwaitingLocation sets the "awaiting_location" field to the value that was provided on create.
func (u *OfflineDownloadUpsert) UpdateAwaitingLocation() *OfflineDownloadUpsert {
	u.SetExcluded(offlinedownload.FieldAwaitingLocation)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OfflineDownloadUpsertOne) UpdateNewValues() *OfflineDownloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(offlinedownload.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OfflineDownloadUpsertOne) Ignore() *OfflineDownloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OfflineDownloadUpsertOne) DoNothing() *OfflineDownloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OfflineDownloadCreate.OnConflict
// documentation for more info.
func (u *OfflineDownloadUpsertOne) Update(set func(*OfflineDownloadUpsert)) *OfflineDownloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OfflineDownloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OfflineDownloadUpsertOne) SetUpdatedAt(v time.Time) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateUpdatedAt() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *OfflineDownloadUpsertOne) SetCode(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateCode() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateCode()
	})
}

// SetJavdbID sets the "javdb_id" field.
func (u *OfflineDownloadUpsertOne) SetJavdbID(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetJavdbID(v)
	})
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateJavdbID() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateJavdbID()
	})
}

// SetHash sets the "hash" field.
func (u *OfflineDownloadUpsertOne) SetHash(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateHash() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateHash()
	})
}

// SetInfoHash sets the "info_hash" field.
func (u *OfflineDownloadUpsertOne) SetInfoHash(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetInfoHash(v)
	})
}

// UpdateInfoHash sets the "info_hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateInfoHash() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateInfoHash()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OfflineDownloadUpsertOne) SetAccountID(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateAccountID() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateAccountID()
	})
}

// SetDirectoryID sets the "directory_id" field.
func (u *OfflineDownloadUpsertOne) SetDirectoryID(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetDirectoryID(v)
	})
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateDirectoryID() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateDirectoryID()
	})
}

// SetStatus sets the "status" field.
func (u *OfflineDownloadUpsertOne) SetStatus(v offlinedownload.Status) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateStatus() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateStatus()
	})
}

// SetRecovery sets the "recovery" field.
func (u *OfflineDownloadUpsertOne) SetRecovery(v *download.Recovery) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetRecovery(v)
	})
}

// UpdateRecovery sets the "recovery" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateRecovery() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateRecovery()
	})
}

// ClearRecovery clears the value of the "recovery" field.
func (u *OfflineDownloadUpsertOne) ClearRecovery() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.ClearRecovery()
	})
}

// SetProgress sets the "progress" field.
func (u *OfflineDownloadUpsertOne) SetProgress(v int) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *OfflineDownloadUpsertOne) AddProgress(v int) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateProgress() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateProgress()
	})
}

// SetError sets the "error" field.
func (u *OfflineDownloadUpsertOne) SetError(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateError() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *OfflineDownloadUpsertOne) ClearError() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.ClearError()
	})
}

// SetFileID sets the "file_id" field.
func (u *OfflineDownloadUpsertOne) SetFileID(v string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateFileID() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateFileID()
	})
}

// SetFileIds sets the "file_ids" field.
func (u *OfflineDownloadUpsertOne) SetFileIds(v []string) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetFileIds(v)
	})
}

// UpdateFileIds sets the "file_ids" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateFileIds() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateFileIds()
	})
}

// SetScanTaskID sets the "scan_task_id" field.
func (u *OfflineDownloadUpsertOne) SetScanTaskID(v int) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetScanTaskID(v)
	})
}

// AddScanTaskID adds v to the "scan_task_id" field.
func (u *OfflineDownloadUpsertOne) AddScanTaskID(v int) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.AddScanTaskID(v)
	})
}

// UpdateScanTaskID sets the "scan_task_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateScanTaskID() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateScanTaskID()
	})
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (u *OfflineDownloadUpsertOne) SetAwaitingLocation(v bool) *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetAwaitingLocation(v)
	})
}

// UpdateAwaitingLocation sets the "awaiting_location" field to the value that was provided on create.
func (u *OfflineDownloadUpsertOne) UpdateAwaitingLocation() *OfflineDownloadUpsertOne {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateAwaitingLocation()
	})
}

// Exec executes the query.
func (u *OfflineDownloadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OfflineDownloadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OfflineDownloadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OfflineDownloadUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OfflineDownloadUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OfflineDownloadCreateBulk is the builder for creating many OfflineDownload entities in bulk.
type OfflineDownloadCreateBulk struct {
	config
	err      error
	builders []*OfflineDownloadCreate
	conflict []sql.ConflictOption
}

// Save creates the OfflineDownload entities in the database.
func (_c *OfflineDownloadCreateBulk) Save(ctx context.Context) ([]*OfflineDownload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OfflineDownload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OfflineDownloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OfflineDownloadCreateBulk) SaveX(ctx context.Context) []*OfflineDownload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineDownloadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineDownloadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OfflineDownload.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OfflineDownloadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OfflineDownloadCreateBulk) OnConflict(opts ...sql.ConflictOption) *OfflineDownloadUpsertBulk {
	_c.conflict = opts
	return &OfflineDownloadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OfflineDownloadCreateBulk) OnConflictColumns(columns ...string) *OfflineDownloadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OfflineDownloadUpsertBulk{
		create: _c,
	}
}

// OfflineDownloadUpsertBulk is the builder for "upsert"-ing
// a bulk of OfflineDownload nodes.
type OfflineDownloadUpsertBulk struct {
	create *OfflineDownloadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OfflineDownloadUpsertBulk) UpdateNewValues() *OfflineDownloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(offlinedownload.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OfflineDownload.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OfflineDownloadUpsertBulk) Ignore() *OfflineDownloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OfflineDownloadUpsertBulk) DoNothing() *OfflineDownloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OfflineDownloadCreateBulk.OnConflict
// documentation for more info.
func (u *OfflineDownloadUpsertBulk) Update(set func(*OfflineDownloadUpsert)) *OfflineDownloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OfflineDownloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OfflineDownloadUpsertBulk) SetUpdatedAt(v time.Time) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateUpdatedAt() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *OfflineDownloadUpsertBulk) SetCode(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateCode() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateCode()
	})
}

// SetJavdbID sets the "javdb_id" field.
func (u *OfflineDownloadUpsertBulk) SetJavdbID(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetJavdbID(v)
	})
}

// UpdateJavdbID sets the "javdb_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateJavdbID() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateJavdbID()
	})
}

// SetHash sets the "hash" field.
func (u *OfflineDownloadUpsertBulk) SetHash(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateHash() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateHash()
	})
}

// SetInfoHash sets the "info_hash" field.
func (u *OfflineDownloadUpsertBulk) SetInfoHash(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetInfoHash(v)
	})
}

// UpdateInfoHash sets the "info_hash" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateInfoHash() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateInfoHash()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OfflineDownloadUpsertBulk) SetAccountID(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateAccountID() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateAccountID()
	})
}

// SetDirectoryID sets the "directory_id" field.
func (u *OfflineDownloadUpsertBulk) SetDirectoryID(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetDirectoryID(v)
	})
}

// UpdateDirectoryID sets the "directory_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateDirectoryID() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateDirectoryID()
	})
}

// SetStatus sets the "status" field.
func (u *OfflineDownloadUpsertBulk) SetStatus(v offlinedownload.Status) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateStatus() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateStatus()
	})
}

// SetRecovery sets the "recovery" field.
func (u *OfflineDownloadUpsertBulk) SetRecovery(v *download.Recovery) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetRecovery(v)
	})
}

// UpdateRecovery sets the "recovery" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateRecovery() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateRecovery()
	})
}

// ClearRecovery clears the value of the "recovery" field.
func (u *OfflineDownloadUpsertBulk) ClearRecovery() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.ClearRecovery()
	})
}

// SetProgress sets the "progress" field.
func (u *OfflineDownloadUpsertBulk) SetProgress(v int) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *OfflineDownloadUpsertBulk) AddProgress(v int) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateProgress() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateProgress()
	})
}

// SetError sets the "error" field.
func (u *OfflineDownloadUpsertBulk) SetError(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateError() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *OfflineDownloadUpsertBulk) ClearError() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.ClearError()
	})
}

// SetFileID sets the "file_id" field.
func (u *OfflineDownloadUpsertBulk) SetFileID(v string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateFileID() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateFileID()
	})
}

// SetFileIds sets the "file_ids" field.
func (u *OfflineDownloadUpsertBulk) SetFileIds(v []string) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetFileIds(v)
	})
}

// UpdateFileIds sets the "file_ids" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateFileIds() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateFileIds()
	})
}

// SetScanTaskID sets the "scan_task_id" field.
func (u *OfflineDownloadUpsertBulk) SetScanTaskID(v int) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetScanTaskID(v)
	})
}

// AddScanTaskID adds v to the "scan_task_id" field.
func (u *OfflineDownloadUpsertBulk) AddScanTaskID(v int) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.AddScanTaskID(v)
	})
}

// UpdateScanTaskID sets the "scan_task_id" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateScanTaskID() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateScanTaskID()
	})
}

// SetAwaitingLocation sets the "awaiting_location" field.
func (u *OfflineDownloadUpsertBulk) SetAwaitingLocation(v bool) *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.SetAwaitingLocation(v)
	})
}

// UpdateAwaitingLocation sets the "awaiting_location" field to the value that was provided on create.
func (u *OfflineDownloadUpsertBulk) UpdateAwaitingLocation() *OfflineDownloadUpsertBulk {
	return u.Update(func(s *OfflineDownloadUpsert) {
		s.UpdateAwaitingLocation()
	})
}

// Exec executes the query.
func (u *OfflineDownloadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OfflineDownloadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OfflineDownloadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OfflineDownloadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
