// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Actor is the predicate function for actor builders.
type Actor func(*sql.Selector)

// EmbyNotification is the predicate function for embynotification builders.
type EmbyNotification func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// MetadataCache is the predicate function for metadatacache builders.
type MetadataCache func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// OfflineDownload is the predicate function for offlinedownload builders.
type OfflineDownload func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// Subtitle is the predicate function for subtitle builders.
type Subtitle func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// ViewedMovie is the predicate function for viewedmovie builders.
type ViewedMovie func(*sql.Selector)
