// Code generated by ent, DO NOT EDIT.

package offlinedownload

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the offlinedownload type in the database.
	Label = "offline_download"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldJavdbID holds the string denoting the javdb_id field in the database.
	FieldJavdbID = "javdb_id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldInfoHash holds the string denoting the info_hash field in the database.
	FieldInfoHash = "info_hash"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldDirectoryID holds the string denoting the directory_id field in the database.
	FieldDirectoryID = "directory_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRecovery holds the string denoting the recovery field in the database.
	FieldRecovery = "recovery"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldFileIds holds the string denoting the file_ids field in the database.
	FieldFileIds = "file_ids"
	// FieldScanTaskID holds the string denoting the scan_task_id field in the database.
	FieldScanTaskID = "scan_task_id"
	// FieldAwaitingLocation holds the string denoting the awaiting_location field in the database.
	FieldAwaitingLocation = "awaiting_location"
	// Table holds the table name of the offlinedownload in the database.
	Table = "offline_downloads"
)

// Columns holds all SQL columns for offlinedownload fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCode,
	FieldJavdbID,
	FieldHash,
	FieldInfoHash,
	FieldAccountID,
	FieldDirectoryID,
	FieldStatus,
	FieldRecovery,
	FieldProgress,
	FieldError,
	FieldFileID,
	FieldFileIds,
	FieldScanTaskID,
	FieldAwaitingLocation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCode holds the default value on creation for the "code" field.
	DefaultCode string
	// DefaultJavdbID holds the default value on creation for the "javdb_id" field.
	DefaultJavdbID string
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// DefaultInfoHash holds the default value on creation for the "info_hash" field.
	DefaultInfoHash string
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultDirectoryID holds the default value on creation for the "directory_id" field.
	DefaultDirectoryID string
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int
	// ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	ProgressValidator func(int) error
	// DefaultFileID holds the default value on creation for the "file_id" field.
	DefaultFileID string
	// DefaultFileIds holds the default value on creation for the "file_ids" field.
	DefaultFileIds []string
	// DefaultScanTaskID holds the default value on creation for the "scan_task_id" field.
	DefaultScanTaskID int
	// DefaultAwaitingLocation holds the default value on creation for the "awaiting_location" field.
	DefaultAwaitingLocation bool
)

// Status defines the type for the "status" enum field.
type Status string

// StatusRunning is the default value of the Status enum.
const DefaultStatus = StatusRunning

// Status values.
const (
	StatusRunning   Status = "running"
	StatusDone      Status = "done"
	StatusFailed    Status = "failed"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusRunning, StatusDone, StatusFailed, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("offlinedownload: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the OfflineDownload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByJavdbID orders the results by the javdb_id field.
func ByJavdbID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJavdbID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByInfoHash orders the results by the info_hash field.
func ByInfoHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInfoHash, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByDirectoryID orders the results by the directory_id field.
func ByDirectoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirectoryID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}

// ByScanTaskID orders the results by the scan_task_id field.
func ByScanTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanTaskID, opts...).ToFunc()
}

// ByAwaitingLocation orders the results by the awaiting_location field.
func ByAwaitingLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAwaitingLocation, opts...).ToFunc()
}
