// Code generated by ent, DO NOT EDIT.

package actor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldProvider, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldSourceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldName, v))
}

// NameZht applies equality check predicate on the "name_zht" field. It's identical to NameZhtEQ.
func NameZht(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldNameZht, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldAvatar, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldProvider, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldSourceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldName, v))
}

// NameZhtEQ applies the EQ predicate on the "name_zht" field.
func NameZhtEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldNameZht, v))
}

// NameZhtNEQ applies the NEQ predicate on the "name_zht" field.
func NameZhtNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldNameZht, v))
}

// NameZhtIn applies the In predicate on the "name_zht" field.
func NameZhtIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldNameZht, vs...))
}

// NameZhtNotIn applies the NotIn predicate on the "name_zht" field.
func NameZhtNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldNameZht, vs...))
}

// NameZhtGT applies the GT predicate on the "name_zht" field.
func NameZhtGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldNameZht, v))
}

// NameZhtGTE applies the GTE predicate on the "name_zht" field.
func NameZhtGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldNameZht, v))
}

// NameZhtLT applies the LT predicate on the "name_zht" field.
func NameZhtLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldNameZht, v))
}

// NameZhtLTE applies the LTE predicate on the "name_zht" field.
func NameZhtLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldNameZht, v))
}

// NameZhtContains applies the Contains predicate on the "name_zht" field.
func NameZhtContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldNameZht, v))
}

// NameZhtHasPrefix applies the HasPrefix predicate on the "name_zht" field.
func NameZhtHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldNameZht, v))
}

// NameZhtHasSuffix applies the HasSuffix predicate on the "name_zht" field.
func NameZhtHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldNameZht, v))
}

// NameZhtIsNil applies the IsNil predicate on the "name_zht" field.
func NameZhtIsNil() predicate.Actor {
	return predicate.Actor(sql.FieldIsNull(FieldNameZht))
}

// NameZhtNotNil applies the NotNil predicate on the "name_zht" field.
func NameZhtNotNil() predicate.Actor {
	return predicate.Actor(sql.FieldNotNull(FieldNameZht))
}

// NameZhtEqualFold applies the EqualFold predicate on the "name_zht" field.
func NameZhtEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldNameZht, v))
}

// NameZhtContainsFold applies the ContainsFold predicate on the "name_zht" field.
func NameZhtContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldNameZht, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v Gender) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v Gender) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...Gender) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...Gender) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldGender, vs...))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.Actor {
	return predicate.Actor(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.Actor {
	return predicate.Actor(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.Actor {
	return predicate.Actor(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.Actor {
	return predicate.Actor(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarIsNil applies the IsNil predicate on the "avatar" field.
func AvatarIsNil() predicate.Actor {
	return predicate.Actor(sql.FieldIsNull(FieldAvatar))
}

// AvatarNotNil applies the NotNil predicate on the "avatar" field.
func AvatarNotNil() predicate.Actor {
	return predicate.Actor(sql.FieldNotNull(FieldAvatar))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.Actor {
	return predicate.Actor(sql.FieldContainsFold(FieldAvatar, v))
}

// HasMovies applies the HasEdge predicate on the "movies" edge.
func HasMovies() predicate.Actor {
	return predicate.Actor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, MoviesTable, MoviesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMoviesWith applies the HasEdge predicate on the "movies" edge with a given conditions (other predicates).
func HasMoviesWith(preds ...predicate.Movie) predicate.Actor {
	return predicate.Actor(func(s *sql.Selector) {
		step := newMoviesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Actor) predicate.Actor {
	return predicate.Actor(sql.NotPredicates(p))
}
